// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apps/order/rpc/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderSource   int32                  `protobuf:"varint,3,opt,name=order_source,json=orderSource,proto3" json:"order_source,omitempty"` // 1=normal,2=seckill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderReq) GetOrderSource() int32 {
	if x != nil {
		return x.OrderSource
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateOrderFromSeckillReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId        int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId    int64                  `protobuf:"varint,3,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	ProductId         int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity          int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SeckillPriceCent  int64                  `protobuf:"varint,6,opt,name=seckill_price_cent,json=seckillPriceCent,proto3" json:"seckill_price_cent,omitempty"`
	SnapshotName      string                 `protobuf:"bytes,7,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	SnapshotMainImage string                 `protobuf:"bytes,8,opt,name=snapshot_main_image,json=snapshotMainImage,proto3" json:"snapshot_main_image,omitempty"`
	SkuCode           string                 `protobuf:"bytes,9,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderFromSeckillReq) Reset() {
	*x = CreateOrderFromSeckillReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderFromSeckillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderFromSeckillReq) ProtoMessage() {}

func (x *CreateOrderFromSeckillReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderFromSeckillReq.ProtoReflect.Descriptor instead.
func (*CreateOrderFromSeckillReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderFromSeckillReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderFromSeckillReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CreateOrderFromSeckillReq) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *CreateOrderFromSeckillReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderFromSeckillReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderFromSeckillReq) GetSeckillPriceCent() int64 {
	if x != nil {
		return x.SeckillPriceCent
	}
	return 0
}

func (x *CreateOrderFromSeckillReq) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

func (x *CreateOrderFromSeckillReq) GetSnapshotMainImage() string {
	if x != nil {
		return x.SnapshotMainImage
	}
	return ""
}

func (x *CreateOrderFromSeckillReq) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *CreateOrderFromSeckillReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateOrderFromSeckillResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderFromSeckillResp) Reset() {
	*x = CreateOrderFromSeckillResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderFromSeckillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderFromSeckillResp) ProtoMessage() {}

func (x *CreateOrderFromSeckillResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderFromSeckillResp.ProtoReflect.Descriptor instead.
func (*CreateOrderFromSeckillResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderFromSeckillResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type ConfirmPaymentAndInfoReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId         int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PayChannel      string                 `protobuf:"bytes,3,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	PayReference    string                 `protobuf:"bytes,4,opt,name=pay_reference,json=payReference,proto3" json:"pay_reference,omitempty"`
	ReceiverName    string                 `protobuf:"bytes,5,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone   string                 `protobuf:"bytes,6,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,7,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	BuyerRemark     string                 `protobuf:"bytes,8,opt,name=buyer_remark,json=buyerRemark,proto3" json:"buyer_remark,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmPaymentAndInfoReq) Reset() {
	*x = ConfirmPaymentAndInfoReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentAndInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentAndInfoReq) ProtoMessage() {}

func (x *ConfirmPaymentAndInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentAndInfoReq.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentAndInfoReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPaymentAndInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmPaymentAndInfoReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ConfirmPaymentAndInfoReq) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *ConfirmPaymentAndInfoReq) GetPayReference() string {
	if x != nil {
		return x.PayReference
	}
	return ""
}

func (x *ConfirmPaymentAndInfoReq) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *ConfirmPaymentAndInfoReq) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *ConfirmPaymentAndInfoReq) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *ConfirmPaymentAndInfoReq) GetBuyerRemark() string {
	if x != nil {
		return x.BuyerRemark
	}
	return ""
}

type ConfirmPaymentAndInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentAndInfoResp) Reset() {
	*x = ConfirmPaymentAndInfoResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentAndInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentAndInfoResp) ProtoMessage() {}

func (x *ConfirmPaymentAndInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentAndInfoResp.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentAndInfoResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentAndInfoResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type ConfirmReceiptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReceiptReq) Reset() {
	*x = ConfirmReceiptReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReceiptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceiptReq) ProtoMessage() {}

func (x *ConfirmReceiptReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceiptReq.ProtoReflect.Descriptor instead.
func (*ConfirmReceiptReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmReceiptReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmReceiptReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ConfirmReceiptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReceiptResp) Reset() {
	*x = ConfirmReceiptResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReceiptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReceiptResp) ProtoMessage() {}

func (x *ConfirmReceiptResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReceiptResp.ProtoReflect.Descriptor instead.
func (*ConfirmReceiptResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmReceiptResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderUserReq) Reset() {
	*x = GetOrderUserReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderUserReq) ProtoMessage() {}

func (x *GetOrderUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderUserReq.ProtoReflect.Descriptor instead.
func (*GetOrderUserReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderUserReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderUserResp) Reset() {
	*x = GetOrderUserResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderUserResp) ProtoMessage() {}

func (x *GetOrderUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderUserResp.ProtoReflect.Descriptor instead.
func (*GetOrderUserResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderUserResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersUserReq) Reset() {
	*x = ListOrdersUserReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersUserReq) ProtoMessage() {}

func (x *ListOrdersUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersUserReq.ProtoReflect.Descriptor instead.
func (*ListOrdersUserReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{12}
}

func (x *ListOrdersUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersUserReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersUserReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersUserReq) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

type ListOrdersUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderView           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersUserResp) Reset() {
	*x = ListOrdersUserResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersUserResp) ProtoMessage() {}

func (x *ListOrdersUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersUserResp.ProtoReflect.Descriptor instead.
func (*ListOrdersUserResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersUserResp) GetList() []*OrderView {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOrdersUserResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersUserResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersUserResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ReviewOrderAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewOrderAdminReq) Reset() {
	*x = ReviewOrderAdminReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewOrderAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewOrderAdminReq) ProtoMessage() {}

func (x *ReviewOrderAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewOrderAdminReq.ProtoReflect.Descriptor instead.
func (*ReviewOrderAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{14}
}

func (x *ReviewOrderAdminReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReviewOrderAdminReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *ReviewOrderAdminReq) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ReviewOrderAdminReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReviewOrderAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewOrderAdminResp) Reset() {
	*x = ReviewOrderAdminResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewOrderAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewOrderAdminResp) ProtoMessage() {}

func (x *ReviewOrderAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewOrderAdminResp.ProtoReflect.Descriptor instead.
func (*ReviewOrderAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{15}
}

func (x *ReviewOrderAdminResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type ShipOrderAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	TrackingNo    string                 `protobuf:"bytes,3,opt,name=tracking_no,json=trackingNo,proto3" json:"tracking_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderAdminReq) Reset() {
	*x = ShipOrderAdminReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderAdminReq) ProtoMessage() {}

func (x *ShipOrderAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderAdminReq.ProtoReflect.Descriptor instead.
func (*ShipOrderAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{16}
}

func (x *ShipOrderAdminReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ShipOrderAdminReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *ShipOrderAdminReq) GetTrackingNo() string {
	if x != nil {
		return x.TrackingNo
	}
	return ""
}

type ShipOrderAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderAdminResp) Reset() {
	*x = ShipOrderAdminResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderAdminResp) ProtoMessage() {}

func (x *ShipOrderAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderAdminResp.ProtoReflect.Descriptor instead.
func (*ShipOrderAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{17}
}

func (x *ShipOrderAdminResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderAdminReq) Reset() {
	*x = GetOrderAdminReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderAdminReq) ProtoMessage() {}

func (x *GetOrderAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderAdminReq.ProtoReflect.Descriptor instead.
func (*GetOrderAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{18}
}

func (x *GetOrderAdminReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderView             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderAdminResp) Reset() {
	*x = GetOrderAdminResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderAdminResp) ProtoMessage() {}

func (x *GetOrderAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderAdminResp.ProtoReflect.Descriptor instead.
func (*GetOrderAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderAdminResp) GetOrder() *OrderView {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	ReviewStatus  int32                  `protobuf:"varint,4,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,6,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersAdminReq) Reset() {
	*x = ListOrdersAdminReq{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersAdminReq) ProtoMessage() {}

func (x *ListOrdersAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersAdminReq.ProtoReflect.Descriptor instead.
func (*ListOrdersAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{20}
}

func (x *ListOrdersAdminReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersAdminReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersAdminReq) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *ListOrdersAdminReq) GetReviewStatus() int32 {
	if x != nil {
		return x.ReviewStatus
	}
	return 0
}

func (x *ListOrdersAdminReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersAdminReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ListOrdersAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderView           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersAdminResp) Reset() {
	*x = ListOrdersAdminResp{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersAdminResp) ProtoMessage() {}

func (x *ListOrdersAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersAdminResp.ProtoReflect.Descriptor instead.
func (*ListOrdersAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{21}
}

func (x *ListOrdersAdminResp) GetList() []*OrderView {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOrdersAdminResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersAdminResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersAdminResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderView struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrderId               int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo               string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId                int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderSource           int32                  `protobuf:"varint,4,opt,name=order_source,json=orderSource,proto3" json:"order_source,omitempty"`
	ProductId             int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode               string                 `protobuf:"bytes,6,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ProductName           string                 `protobuf:"bytes,7,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	MainImage             string                 `protobuf:"bytes,8,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	UnitPriceCent         int64                  `protobuf:"varint,9,opt,name=unit_price_cent,json=unitPriceCent,proto3" json:"unit_price_cent,omitempty"`
	Quantity              int64                  `protobuf:"varint,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalAmountCent       int64                  `protobuf:"varint,11,opt,name=total_amount_cent,json=totalAmountCent,proto3" json:"total_amount_cent,omitempty"`
	OrderStatus           int32                  `protobuf:"varint,12,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus         int32                  `protobuf:"varint,13,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ReviewStatus          int32                  `protobuf:"varint,14,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`
	ShippingStatus        int32                  `protobuf:"varint,15,opt,name=shipping_status,json=shippingStatus,proto3" json:"shipping_status,omitempty"`
	RefundStatus          int32                  `protobuf:"varint,16,opt,name=refund_status,json=refundStatus,proto3" json:"refund_status,omitempty"`
	ReviewMode            int32                  `protobuf:"varint,17,opt,name=review_mode,json=reviewMode,proto3" json:"review_mode,omitempty"`
	PaidAtUnix            int64                  `protobuf:"varint,18,opt,name=paid_at_unix,json=paidAtUnix,proto3" json:"paid_at_unix,omitempty"`
	PayChannel            string                 `protobuf:"bytes,19,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	PayReference          string                 `protobuf:"bytes,20,opt,name=pay_reference,json=payReference,proto3" json:"pay_reference,omitempty"`
	ReceiverName          string                 `protobuf:"bytes,21,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone         string                 `protobuf:"bytes,22,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress       string                 `protobuf:"bytes,23,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	BuyerRemark           string                 `protobuf:"bytes,24,opt,name=buyer_remark,json=buyerRemark,proto3" json:"buyer_remark,omitempty"`
	ReviewDueAtUnix       int64                  `protobuf:"varint,25,opt,name=review_due_at_unix,json=reviewDueAtUnix,proto3" json:"review_due_at_unix,omitempty"`
	ReviewedAtUnix        int64                  `protobuf:"varint,26,opt,name=reviewed_at_unix,json=reviewedAtUnix,proto3" json:"reviewed_at_unix,omitempty"`
	ReviewedBy            int64                  `protobuf:"varint,27,opt,name=reviewed_by,json=reviewedBy,proto3" json:"reviewed_by,omitempty"`
	ReviewReason          string                 `protobuf:"bytes,28,opt,name=review_reason,json=reviewReason,proto3" json:"review_reason,omitempty"`
	ShippedAtUnix         int64                  `protobuf:"varint,29,opt,name=shipped_at_unix,json=shippedAtUnix,proto3" json:"shipped_at_unix,omitempty"`
	ShippedBy             int64                  `protobuf:"varint,30,opt,name=shipped_by,json=shippedBy,proto3" json:"shipped_by,omitempty"`
	TrackingNo            string                 `protobuf:"bytes,31,opt,name=tracking_no,json=trackingNo,proto3" json:"tracking_no,omitempty"`
	RefundDueAtUnix       int64                  `protobuf:"varint,32,opt,name=refund_due_at_unix,json=refundDueAtUnix,proto3" json:"refund_due_at_unix,omitempty"`
	RefundedAtUnix        int64                  `protobuf:"varint,33,opt,name=refunded_at_unix,json=refundedAtUnix,proto3" json:"refunded_at_unix,omitempty"`
	ClosedAtUnix          int64                  `protobuf:"varint,34,opt,name=closed_at_unix,json=closedAtUnix,proto3" json:"closed_at_unix,omitempty"`
	CloseReason           string                 `protobuf:"bytes,35,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	CreatedAtUnix         int64                  `protobuf:"varint,36,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix         int64                  `protobuf:"varint,37,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	SeckillActivityId     int64                  `protobuf:"varint,38,opt,name=seckill_activity_id,json=seckillActivityId,proto3" json:"seckill_activity_id,omitempty"`
	SeckillActivityItemId int64                  `protobuf:"varint,39,opt,name=seckill_activity_item_id,json=seckillActivityItemId,proto3" json:"seckill_activity_item_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OrderView) Reset() {
	*x = OrderView{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderView) ProtoMessage() {}

func (x *OrderView) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderView.ProtoReflect.Descriptor instead.
func (*OrderView) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{22}
}

func (x *OrderView) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderView) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderView) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderView) GetOrderSource() int32 {
	if x != nil {
		return x.OrderSource
	}
	return 0
}

func (x *OrderView) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderView) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *OrderView) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderView) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *OrderView) GetUnitPriceCent() int64 {
	if x != nil {
		return x.UnitPriceCent
	}
	return 0
}

func (x *OrderView) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderView) GetTotalAmountCent() int64 {
	if x != nil {
		return x.TotalAmountCent
	}
	return 0
}

func (x *OrderView) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderView) GetPaymentStatus() int32 {
	if x != nil {
		return x.PaymentStatus
	}
	return 0
}

func (x *OrderView) GetReviewStatus() int32 {
	if x != nil {
		return x.ReviewStatus
	}
	return 0
}

func (x *OrderView) GetShippingStatus() int32 {
	if x != nil {
		return x.ShippingStatus
	}
	return 0
}

func (x *OrderView) GetRefundStatus() int32 {
	if x != nil {
		return x.RefundStatus
	}
	return 0
}

func (x *OrderView) GetReviewMode() int32 {
	if x != nil {
		return x.ReviewMode
	}
	return 0
}

func (x *OrderView) GetPaidAtUnix() int64 {
	if x != nil {
		return x.PaidAtUnix
	}
	return 0
}

func (x *OrderView) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *OrderView) GetPayReference() string {
	if x != nil {
		return x.PayReference
	}
	return ""
}

func (x *OrderView) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderView) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *OrderView) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *OrderView) GetBuyerRemark() string {
	if x != nil {
		return x.BuyerRemark
	}
	return ""
}

func (x *OrderView) GetReviewDueAtUnix() int64 {
	if x != nil {
		return x.ReviewDueAtUnix
	}
	return 0
}

func (x *OrderView) GetReviewedAtUnix() int64 {
	if x != nil {
		return x.ReviewedAtUnix
	}
	return 0
}

func (x *OrderView) GetReviewedBy() int64 {
	if x != nil {
		return x.ReviewedBy
	}
	return 0
}

func (x *OrderView) GetReviewReason() string {
	if x != nil {
		return x.ReviewReason
	}
	return ""
}

func (x *OrderView) GetShippedAtUnix() int64 {
	if x != nil {
		return x.ShippedAtUnix
	}
	return 0
}

func (x *OrderView) GetShippedBy() int64 {
	if x != nil {
		return x.ShippedBy
	}
	return 0
}

func (x *OrderView) GetTrackingNo() string {
	if x != nil {
		return x.TrackingNo
	}
	return ""
}

func (x *OrderView) GetRefundDueAtUnix() int64 {
	if x != nil {
		return x.RefundDueAtUnix
	}
	return 0
}

func (x *OrderView) GetRefundedAtUnix() int64 {
	if x != nil {
		return x.RefundedAtUnix
	}
	return 0
}

func (x *OrderView) GetClosedAtUnix() int64 {
	if x != nil {
		return x.ClosedAtUnix
	}
	return 0
}

func (x *OrderView) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *OrderView) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *OrderView) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *OrderView) GetSeckillActivityId() int64 {
	if x != nil {
		return x.SeckillActivityId
	}
	return 0
}

func (x *OrderView) GetSeckillActivityItemId() int64 {
	if x != nil {
		return x.SeckillActivityItemId
	}
	return 0
}

var File_apps_order_rpc_order_proto protoreflect.FileDescriptor

const file_apps_order_rpc_order_proto_rawDesc = "" +
	"\n" +
	"\x1aapps/order/rpc/order.proto\x12\x05order\"k\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12!\n" +
	"\forder_source\x18\x03 \x01(\x05R\vorderSource\"9\n" +
	"\x0fCreateOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"\x81\x03\n" +
	"\x19CreateOrderFromSeckillReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x03 \x01(\x03R\x0eactivityItemId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12,\n" +
	"\x12seckill_price_cent\x18\x06 \x01(\x03R\x10seckillPriceCent\x12#\n" +
	"\rsnapshot_name\x18\a \x01(\tR\fsnapshotName\x12.\n" +
	"\x13snapshot_main_image\x18\b \x01(\tR\x11snapshotMainImage\x12\x19\n" +
	"\bsku_code\x18\t \x01(\tR\askuCode\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\"D\n" +
	"\x1aCreateOrderFromSeckillResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"\xae\x02\n" +
	"\x18ConfirmPaymentAndInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1f\n" +
	"\vpay_channel\x18\x03 \x01(\tR\n" +
	"payChannel\x12#\n" +
	"\rpay_reference\x18\x04 \x01(\tR\fpayReference\x12#\n" +
	"\rreceiver_name\x18\x05 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x06 \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\a \x01(\tR\x0freceiverAddress\x12!\n" +
	"\fbuyer_remark\x18\b \x01(\tR\vbuyerRemark\"C\n" +
	"\x19ConfirmPaymentAndInfoResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"\\\n" +
	"\x0eCancelOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"9\n" +
	"\x0fCancelOrderResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"G\n" +
	"\x11ConfirmReceiptReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\"<\n" +
	"\x12ConfirmReceiptResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"E\n" +
	"\x0fGetOrderUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\":\n" +
	"\x10GetOrderUserResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"\x80\x01\n" +
	"\x11ListOrdersUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\"\x81\x01\n" +
	"\x12ListOrdersUserResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.order.OrderViewR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\x7f\n" +
	"\x13ReviewOrderAdminReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\">\n" +
	"\x14ReviewOrderAdminResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"j\n" +
	"\x11ShipOrderAdminReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\x12\x1f\n" +
	"\vtracking_no\x18\x03 \x01(\tR\n" +
	"trackingNo\"<\n" +
	"\x12ShipOrderAdminResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"-\n" +
	"\x10GetOrderAdminReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\";\n" +
	"\x11GetOrderAdminResp\x12&\n" +
	"\x05order\x18\x01 \x01(\v2\x10.order.OrderViewR\x05order\"\xc1\x01\n" +
	"\x12ListOrdersAdminReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12!\n" +
	"\forder_status\x18\x03 \x01(\x05R\vorderStatus\x12#\n" +
	"\rreview_status\x18\x04 \x01(\x05R\freviewStatus\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x06 \x01(\tR\aorderNo\"\x82\x01\n" +
	"\x13ListOrdersAdminResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.order.OrderViewR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xa7\v\n" +
	"\tOrderView\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12!\n" +
	"\forder_source\x18\x04 \x01(\x05R\vorderSource\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x06 \x01(\tR\askuCode\x12!\n" +
	"\fproduct_name\x18\a \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"main_image\x18\b \x01(\tR\tmainImage\x12&\n" +
	"\x0funit_price_cent\x18\t \x01(\x03R\runitPriceCent\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\x03R\bquantity\x12*\n" +
	"\x11total_amount_cent\x18\v \x01(\x03R\x0ftotalAmountCent\x12!\n" +
	"\forder_status\x18\f \x01(\x05R\vorderStatus\x12%\n" +
	"\x0epayment_status\x18\r \x01(\x05R\rpaymentStatus\x12#\n" +
	"\rreview_status\x18\x0e \x01(\x05R\freviewStatus\x12'\n" +
	"\x0fshipping_status\x18\x0f \x01(\x05R\x0eshippingStatus\x12#\n" +
	"\rrefund_status\x18\x10 \x01(\x05R\frefundStatus\x12\x1f\n" +
	"\vreview_mode\x18\x11 \x01(\x05R\n" +
	"reviewMode\x12 \n" +
	"\fpaid_at_unix\x18\x12 \x01(\x03R\n" +
	"paidAtUnix\x12\x1f\n" +
	"\vpay_channel\x18\x13 \x01(\tR\n" +
	"payChannel\x12#\n" +
	"\rpay_reference\x18\x14 \x01(\tR\fpayReference\x12#\n" +
	"\rreceiver_name\x18\x15 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x16 \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\x17 \x01(\tR\x0freceiverAddress\x12!\n" +
	"\fbuyer_remark\x18\x18 \x01(\tR\vbuyerRemark\x12+\n" +
	"\x12review_due_at_unix\x18\x19 \x01(\x03R\x0freviewDueAtUnix\x12(\n" +
	"\x10reviewed_at_unix\x18\x1a \x01(\x03R\x0ereviewedAtUnix\x12\x1f\n" +
	"\vreviewed_by\x18\x1b \x01(\x03R\n" +
	"reviewedBy\x12#\n" +
	"\rreview_reason\x18\x1c \x01(\tR\freviewReason\x12&\n" +
	"\x0fshipped_at_unix\x18\x1d \x01(\x03R\rshippedAtUnix\x12\x1d\n" +
	"\n" +
	"shipped_by\x18\x1e \x01(\x03R\tshippedBy\x12\x1f\n" +
	"\vtracking_no\x18\x1f \x01(\tR\n" +
	"trackingNo\x12+\n" +
	"\x12refund_due_at_unix\x18  \x01(\x03R\x0frefundDueAtUnix\x12(\n" +
	"\x10refunded_at_unix\x18! \x01(\x03R\x0erefundedAtUnix\x12$\n" +
	"\x0eclosed_at_unix\x18\" \x01(\x03R\fclosedAtUnix\x12!\n" +
	"\fclose_reason\x18# \x01(\tR\vcloseReason\x12&\n" +
	"\x0fcreated_at_unix\x18$ \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18% \x01(\x03R\rupdatedAtUnix\x12.\n" +
	"\x13seckill_activity_id\x18& \x01(\x03R\x11seckillActivityId\x127\n" +
	"\x18seckill_activity_item_id\x18' \x01(\x03R\x15seckillActivityItemId2\xb2\x06\n" +
	"\bOrderRpc\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12]\n" +
	"\x16CreateOrderFromSeckill\x12 .order.CreateOrderFromSeckillReq\x1a!.order.CreateOrderFromSeckillResp\x12Z\n" +
	"\x15ConfirmPaymentAndInfo\x12\x1f.order.ConfirmPaymentAndInfoReq\x1a .order.ConfirmPaymentAndInfoResp\x12<\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x16.order.CancelOrderResp\x12E\n" +
	"\x0eConfirmReceipt\x12\x18.order.ConfirmReceiptReq\x1a\x19.order.ConfirmReceiptResp\x12?\n" +
	"\fGetOrderUser\x12\x16.order.GetOrderUserReq\x1a\x17.order.GetOrderUserResp\x12E\n" +
	"\x0eListOrdersUser\x12\x18.order.ListOrdersUserReq\x1a\x19.order.ListOrdersUserResp\x12K\n" +
	"\x10ReviewOrderAdmin\x12\x1a.order.ReviewOrderAdminReq\x1a\x1b.order.ReviewOrderAdminResp\x12E\n" +
	"\x0eShipOrderAdmin\x12\x18.order.ShipOrderAdminReq\x1a\x19.order.ShipOrderAdminResp\x12B\n" +
	"\rGetOrderAdmin\x12\x17.order.GetOrderAdminReq\x1a\x18.order.GetOrderAdminResp\x12H\n" +
	"\x0fListOrdersAdmin\x12\x19.order.ListOrdersAdminReq\x1a\x1a.order.ListOrdersAdminRespB Z\x1eflashsale/apps/order/rpc/pb;pbb\x06proto3"

var (
	file_apps_order_rpc_order_proto_rawDescOnce sync.Once
	file_apps_order_rpc_order_proto_rawDescData []byte
)

func file_apps_order_rpc_order_proto_rawDescGZIP() []byte {
	file_apps_order_rpc_order_proto_rawDescOnce.Do(func() {
		file_apps_order_rpc_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_order_rpc_order_proto_rawDesc), len(file_apps_order_rpc_order_proto_rawDesc)))
	})
	return file_apps_order_rpc_order_proto_rawDescData
}

var file_apps_order_rpc_order_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_apps_order_rpc_order_proto_goTypes = []any{
	(*CreateOrderReq)(nil),             // 0: order.CreateOrderReq
	(*CreateOrderResp)(nil),            // 1: order.CreateOrderResp
	(*CreateOrderFromSeckillReq)(nil),  // 2: order.CreateOrderFromSeckillReq
	(*CreateOrderFromSeckillResp)(nil), // 3: order.CreateOrderFromSeckillResp
	(*ConfirmPaymentAndInfoReq)(nil),   // 4: order.ConfirmPaymentAndInfoReq
	(*ConfirmPaymentAndInfoResp)(nil),  // 5: order.ConfirmPaymentAndInfoResp
	(*CancelOrderReq)(nil),             // 6: order.CancelOrderReq
	(*CancelOrderResp)(nil),            // 7: order.CancelOrderResp
	(*ConfirmReceiptReq)(nil),          // 8: order.ConfirmReceiptReq
	(*ConfirmReceiptResp)(nil),         // 9: order.ConfirmReceiptResp
	(*GetOrderUserReq)(nil),            // 10: order.GetOrderUserReq
	(*GetOrderUserResp)(nil),           // 11: order.GetOrderUserResp
	(*ListOrdersUserReq)(nil),          // 12: order.ListOrdersUserReq
	(*ListOrdersUserResp)(nil),         // 13: order.ListOrdersUserResp
	(*ReviewOrderAdminReq)(nil),        // 14: order.ReviewOrderAdminReq
	(*ReviewOrderAdminResp)(nil),       // 15: order.ReviewOrderAdminResp
	(*ShipOrderAdminReq)(nil),          // 16: order.ShipOrderAdminReq
	(*ShipOrderAdminResp)(nil),         // 17: order.ShipOrderAdminResp
	(*GetOrderAdminReq)(nil),           // 18: order.GetOrderAdminReq
	(*GetOrderAdminResp)(nil),          // 19: order.GetOrderAdminResp
	(*ListOrdersAdminReq)(nil),         // 20: order.ListOrdersAdminReq
	(*ListOrdersAdminResp)(nil),        // 21: order.ListOrdersAdminResp
	(*OrderView)(nil),                  // 22: order.OrderView
}
var file_apps_order_rpc_order_proto_depIdxs = []int32{
	22, // 0: order.CreateOrderResp.order:type_name -> order.OrderView
	22, // 1: order.CreateOrderFromSeckillResp.order:type_name -> order.OrderView
	22, // 2: order.ConfirmPaymentAndInfoResp.order:type_name -> order.OrderView
	22, // 3: order.CancelOrderResp.order:type_name -> order.OrderView
	22, // 4: order.ConfirmReceiptResp.order:type_name -> order.OrderView
	22, // 5: order.GetOrderUserResp.order:type_name -> order.OrderView
	22, // 6: order.ListOrdersUserResp.list:type_name -> order.OrderView
	22, // 7: order.ReviewOrderAdminResp.order:type_name -> order.OrderView
	22, // 8: order.ShipOrderAdminResp.order:type_name -> order.OrderView
	22, // 9: order.GetOrderAdminResp.order:type_name -> order.OrderView
	22, // 10: order.ListOrdersAdminResp.list:type_name -> order.OrderView
	0,  // 11: order.OrderRpc.CreateOrder:input_type -> order.CreateOrderReq
	2,  // 12: order.OrderRpc.CreateOrderFromSeckill:input_type -> order.CreateOrderFromSeckillReq
	4,  // 13: order.OrderRpc.ConfirmPaymentAndInfo:input_type -> order.ConfirmPaymentAndInfoReq
	6,  // 14: order.OrderRpc.CancelOrder:input_type -> order.CancelOrderReq
	8,  // 15: order.OrderRpc.ConfirmReceipt:input_type -> order.ConfirmReceiptReq
	10, // 16: order.OrderRpc.GetOrderUser:input_type -> order.GetOrderUserReq
	12, // 17: order.OrderRpc.ListOrdersUser:input_type -> order.ListOrdersUserReq
	14, // 18: order.OrderRpc.ReviewOrderAdmin:input_type -> order.ReviewOrderAdminReq
	16, // 19: order.OrderRpc.ShipOrderAdmin:input_type -> order.ShipOrderAdminReq
	18, // 20: order.OrderRpc.GetOrderAdmin:input_type -> order.GetOrderAdminReq
	20, // 21: order.OrderRpc.ListOrdersAdmin:input_type -> order.ListOrdersAdminReq
	1,  // 22: order.OrderRpc.CreateOrder:output_type -> order.CreateOrderResp
	3,  // 23: order.OrderRpc.CreateOrderFromSeckill:output_type -> order.CreateOrderFromSeckillResp
	5,  // 24: order.OrderRpc.ConfirmPaymentAndInfo:output_type -> order.ConfirmPaymentAndInfoResp
	7,  // 25: order.OrderRpc.CancelOrder:output_type -> order.CancelOrderResp
	9,  // 26: order.OrderRpc.ConfirmReceipt:output_type -> order.ConfirmReceiptResp
	11, // 27: order.OrderRpc.GetOrderUser:output_type -> order.GetOrderUserResp
	13, // 28: order.OrderRpc.ListOrdersUser:output_type -> order.ListOrdersUserResp
	15, // 29: order.OrderRpc.ReviewOrderAdmin:output_type -> order.ReviewOrderAdminResp
	17, // 30: order.OrderRpc.ShipOrderAdmin:output_type -> order.ShipOrderAdminResp
	19, // 31: order.OrderRpc.GetOrderAdmin:output_type -> order.GetOrderAdminResp
	21, // 32: order.OrderRpc.ListOrdersAdmin:output_type -> order.ListOrdersAdminResp
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_apps_order_rpc_order_proto_init() }
func file_apps_order_rpc_order_proto_init() {
	if File_apps_order_rpc_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_order_rpc_order_proto_rawDesc), len(file_apps_order_rpc_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_order_rpc_order_proto_goTypes,
		DependencyIndexes: file_apps_order_rpc_order_proto_depIdxs,
		MessageInfos:      file_apps_order_rpc_order_proto_msgTypes,
	}.Build()
	File_apps_order_rpc_order_proto = out.File
	file_apps_order_rpc_order_proto_goTypes = nil
	file_apps_order_rpc_order_proto_depIdxs = nil
}
