// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: apps/order/rpc/order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderRpc_CreateOrder_FullMethodName            = "/order.OrderRpc/CreateOrder"
	OrderRpc_CreateOrderFromSeckill_FullMethodName = "/order.OrderRpc/CreateOrderFromSeckill"
	OrderRpc_ConfirmPaymentAndInfo_FullMethodName  = "/order.OrderRpc/ConfirmPaymentAndInfo"
	OrderRpc_CancelOrder_FullMethodName            = "/order.OrderRpc/CancelOrder"
	OrderRpc_ConfirmReceipt_FullMethodName         = "/order.OrderRpc/ConfirmReceipt"
	OrderRpc_GetOrderUser_FullMethodName           = "/order.OrderRpc/GetOrderUser"
	OrderRpc_ListOrdersUser_FullMethodName         = "/order.OrderRpc/ListOrdersUser"
	OrderRpc_ReviewOrderAdmin_FullMethodName       = "/order.OrderRpc/ReviewOrderAdmin"
	OrderRpc_ShipOrderAdmin_FullMethodName         = "/order.OrderRpc/ShipOrderAdmin"
	OrderRpc_GetOrderAdmin_FullMethodName          = "/order.OrderRpc/GetOrderAdmin"
	OrderRpc_ListOrdersAdmin_FullMethodName        = "/order.OrderRpc/ListOrdersAdmin"
)

// OrderRpcClient is the client API for OrderRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderRpcClient interface {
	// 用户侧接口
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	CreateOrderFromSeckill(ctx context.Context, in *CreateOrderFromSeckillReq, opts ...grpc.CallOption) (*CreateOrderFromSeckillResp, error)
	ConfirmPaymentAndInfo(ctx context.Context, in *ConfirmPaymentAndInfoReq, opts ...grpc.CallOption) (*ConfirmPaymentAndInfoResp, error)
	CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
	ConfirmReceipt(ctx context.Context, in *ConfirmReceiptReq, opts ...grpc.CallOption) (*ConfirmReceiptResp, error)
	GetOrderUser(ctx context.Context, in *GetOrderUserReq, opts ...grpc.CallOption) (*GetOrderUserResp, error)
	ListOrdersUser(ctx context.Context, in *ListOrdersUserReq, opts ...grpc.CallOption) (*ListOrdersUserResp, error)
	// 管理侧接口
	ReviewOrderAdmin(ctx context.Context, in *ReviewOrderAdminReq, opts ...grpc.CallOption) (*ReviewOrderAdminResp, error)
	ShipOrderAdmin(ctx context.Context, in *ShipOrderAdminReq, opts ...grpc.CallOption) (*ShipOrderAdminResp, error)
	GetOrderAdmin(ctx context.Context, in *GetOrderAdminReq, opts ...grpc.CallOption) (*GetOrderAdminResp, error)
	ListOrdersAdmin(ctx context.Context, in *ListOrdersAdminReq, opts ...grpc.CallOption) (*ListOrdersAdminResp, error)
}

type orderRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderRpcClient(cc grpc.ClientConnInterface) OrderRpcClient {
	return &orderRpcClient{cc}
}

func (c *orderRpcClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, OrderRpc_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) CreateOrderFromSeckill(ctx context.Context, in *CreateOrderFromSeckillReq, opts ...grpc.CallOption) (*CreateOrderFromSeckillResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderFromSeckillResp)
	err := c.cc.Invoke(ctx, OrderRpc_CreateOrderFromSeckill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) ConfirmPaymentAndInfo(ctx context.Context, in *ConfirmPaymentAndInfoReq, opts ...grpc.CallOption) (*ConfirmPaymentAndInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPaymentAndInfoResp)
	err := c.cc.Invoke(ctx, OrderRpc_ConfirmPaymentAndInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResp)
	err := c.cc.Invoke(ctx, OrderRpc_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) ConfirmReceipt(ctx context.Context, in *ConfirmReceiptReq, opts ...grpc.CallOption) (*ConfirmReceiptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmReceiptResp)
	err := c.cc.Invoke(ctx, OrderRpc_ConfirmReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) GetOrderUser(ctx context.Context, in *GetOrderUserReq, opts ...grpc.CallOption) (*GetOrderUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderUserResp)
	err := c.cc.Invoke(ctx, OrderRpc_GetOrderUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) ListOrdersUser(ctx context.Context, in *ListOrdersUserReq, opts ...grpc.CallOption) (*ListOrdersUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersUserResp)
	err := c.cc.Invoke(ctx, OrderRpc_ListOrdersUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) ReviewOrderAdmin(ctx context.Context, in *ReviewOrderAdminReq, opts ...grpc.CallOption) (*ReviewOrderAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewOrderAdminResp)
	err := c.cc.Invoke(ctx, OrderRpc_ReviewOrderAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) ShipOrderAdmin(ctx context.Context, in *ShipOrderAdminReq, opts ...grpc.CallOption) (*ShipOrderAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipOrderAdminResp)
	err := c.cc.Invoke(ctx, OrderRpc_ShipOrderAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) GetOrderAdmin(ctx context.Context, in *GetOrderAdminReq, opts ...grpc.CallOption) (*GetOrderAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderAdminResp)
	err := c.cc.Invoke(ctx, OrderRpc_GetOrderAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) ListOrdersAdmin(ctx context.Context, in *ListOrdersAdminReq, opts ...grpc.CallOption) (*ListOrdersAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersAdminResp)
	err := c.cc.Invoke(ctx, OrderRpc_ListOrdersAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderRpcServer is the server API for OrderRpc service.
// All implementations must embed UnimplementedOrderRpcServer
// for forward compatibility.
type OrderRpcServer interface {
	// 用户侧接口
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	CreateOrderFromSeckill(context.Context, *CreateOrderFromSeckillReq) (*CreateOrderFromSeckillResp, error)
	ConfirmPaymentAndInfo(context.Context, *ConfirmPaymentAndInfoReq) (*ConfirmPaymentAndInfoResp, error)
	CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error)
	ConfirmReceipt(context.Context, *ConfirmReceiptReq) (*ConfirmReceiptResp, error)
	GetOrderUser(context.Context, *GetOrderUserReq) (*GetOrderUserResp, error)
	ListOrdersUser(context.Context, *ListOrdersUserReq) (*ListOrdersUserResp, error)
	// 管理侧接口
	ReviewOrderAdmin(context.Context, *ReviewOrderAdminReq) (*ReviewOrderAdminResp, error)
	ShipOrderAdmin(context.Context, *ShipOrderAdminReq) (*ShipOrderAdminResp, error)
	GetOrderAdmin(context.Context, *GetOrderAdminReq) (*GetOrderAdminResp, error)
	ListOrdersAdmin(context.Context, *ListOrdersAdminReq) (*ListOrdersAdminResp, error)
	mustEmbedUnimplementedOrderRpcServer()
}

// UnimplementedOrderRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderRpcServer struct{}

func (UnimplementedOrderRpcServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderRpcServer) CreateOrderFromSeckill(context.Context, *CreateOrderFromSeckillReq) (*CreateOrderFromSeckillResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrderFromSeckill not implemented")
}
func (UnimplementedOrderRpcServer) ConfirmPaymentAndInfo(context.Context, *ConfirmPaymentAndInfoReq) (*ConfirmPaymentAndInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPaymentAndInfo not implemented")
}
func (UnimplementedOrderRpcServer) CancelOrder(context.Context, *CancelOrderReq) (*CancelOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderRpcServer) ConfirmReceipt(context.Context, *ConfirmReceiptReq) (*ConfirmReceiptResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmReceipt not implemented")
}
func (UnimplementedOrderRpcServer) GetOrderUser(context.Context, *GetOrderUserReq) (*GetOrderUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderUser not implemented")
}
func (UnimplementedOrderRpcServer) ListOrdersUser(context.Context, *ListOrdersUserReq) (*ListOrdersUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrdersUser not implemented")
}
func (UnimplementedOrderRpcServer) ReviewOrderAdmin(context.Context, *ReviewOrderAdminReq) (*ReviewOrderAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewOrderAdmin not implemented")
}
func (UnimplementedOrderRpcServer) ShipOrderAdmin(context.Context, *ShipOrderAdminReq) (*ShipOrderAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ShipOrderAdmin not implemented")
}
func (UnimplementedOrderRpcServer) GetOrderAdmin(context.Context, *GetOrderAdminReq) (*GetOrderAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderAdmin not implemented")
}
func (UnimplementedOrderRpcServer) ListOrdersAdmin(context.Context, *ListOrdersAdminReq) (*ListOrdersAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrdersAdmin not implemented")
}
func (UnimplementedOrderRpcServer) mustEmbedUnimplementedOrderRpcServer() {}
func (UnimplementedOrderRpcServer) testEmbeddedByValue()                  {}

// UnsafeOrderRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderRpcServer will
// result in compilation errors.
type UnsafeOrderRpcServer interface {
	mustEmbedUnimplementedOrderRpcServer()
}

func RegisterOrderRpcServer(s grpc.ServiceRegistrar, srv OrderRpcServer) {
	// If the following call panics, it indicates UnimplementedOrderRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderRpc_ServiceDesc, srv)
}

func _OrderRpc_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_CreateOrderFromSeckill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderFromSeckillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).CreateOrderFromSeckill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_CreateOrderFromSeckill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).CreateOrderFromSeckill(ctx, req.(*CreateOrderFromSeckillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_ConfirmPaymentAndInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentAndInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).ConfirmPaymentAndInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_ConfirmPaymentAndInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).ConfirmPaymentAndInfo(ctx, req.(*ConfirmPaymentAndInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).CancelOrder(ctx, req.(*CancelOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_ConfirmReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmReceiptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).ConfirmReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_ConfirmReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).ConfirmReceipt(ctx, req.(*ConfirmReceiptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_GetOrderUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).GetOrderUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_GetOrderUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).GetOrderUser(ctx, req.(*GetOrderUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_ListOrdersUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).ListOrdersUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_ListOrdersUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).ListOrdersUser(ctx, req.(*ListOrdersUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_ReviewOrderAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewOrderAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).ReviewOrderAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_ReviewOrderAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).ReviewOrderAdmin(ctx, req.(*ReviewOrderAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_ShipOrderAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipOrderAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).ShipOrderAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_ShipOrderAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).ShipOrderAdmin(ctx, req.(*ShipOrderAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_GetOrderAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).GetOrderAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_GetOrderAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).GetOrderAdmin(ctx, req.(*GetOrderAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_ListOrdersAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).ListOrdersAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_ListOrdersAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).ListOrdersAdmin(ctx, req.(*ListOrdersAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderRpc_ServiceDesc is the grpc.ServiceDesc for OrderRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderRpc",
	HandlerType: (*OrderRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderRpc_CreateOrder_Handler,
		},
		{
			MethodName: "CreateOrderFromSeckill",
			Handler:    _OrderRpc_CreateOrderFromSeckill_Handler,
		},
		{
			MethodName: "ConfirmPaymentAndInfo",
			Handler:    _OrderRpc_ConfirmPaymentAndInfo_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderRpc_CancelOrder_Handler,
		},
		{
			MethodName: "ConfirmReceipt",
			Handler:    _OrderRpc_ConfirmReceipt_Handler,
		},
		{
			MethodName: "GetOrderUser",
			Handler:    _OrderRpc_GetOrderUser_Handler,
		},
		{
			MethodName: "ListOrdersUser",
			Handler:    _OrderRpc_ListOrdersUser_Handler,
		},
		{
			MethodName: "ReviewOrderAdmin",
			Handler:    _OrderRpc_ReviewOrderAdmin_Handler,
		},
		{
			MethodName: "ShipOrderAdmin",
			Handler:    _OrderRpc_ShipOrderAdmin_Handler,
		},
		{
			MethodName: "GetOrderAdmin",
			Handler:    _OrderRpc_GetOrderAdmin_Handler,
		},
		{
			MethodName: "ListOrdersAdmin",
			Handler:    _OrderRpc_ListOrdersAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/order/rpc/order.proto",
}
