CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL,
  order_no VARCHAR(32) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  order_source TINYINT NOT NULL DEFAULT 1,
  product_id BIGINT UNSIGNED NOT NULL,
  sku_code VARCHAR(32) NOT NULL,
  product_name VARCHAR(100) NOT NULL,
  main_image VARCHAR(512) NOT NULL,
  unit_price_cent BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  total_amount_cent BIGINT UNSIGNED NOT NULL,
  order_status TINYINT NOT NULL,
  payment_status TINYINT NOT NULL,
  review_status TINYINT NOT NULL,
  shipping_status TINYINT NOT NULL,
  refund_status TINYINT NOT NULL,
  review_mode TINYINT NOT NULL DEFAULT 1,
  paid_at DATETIME NULL,
  pay_channel VARCHAR(32) NOT NULL DEFAULT '',
  pay_reference VARCHAR(64) NOT NULL DEFAULT '',
  receiver_name VARCHAR(64) NOT NULL DEFAULT '',
  receiver_phone VARCHAR(32) NOT NULL DEFAULT '',
  receiver_address VARCHAR(512) NOT NULL DEFAULT '',
  buyer_remark VARCHAR(200) NOT NULL DEFAULT '',
  review_due_at DATETIME NULL,
  reviewed_at DATETIME NULL,
  reviewed_by BIGINT NULL,
  review_reason VARCHAR(200) NOT NULL DEFAULT '',
  shipped_at DATETIME NULL,
  shipped_by BIGINT NULL,
  tracking_no VARCHAR(64) NOT NULL DEFAULT '',
  refund_due_at DATETIME NULL,
  refunded_at DATETIME NULL,
  stock_released TINYINT NOT NULL DEFAULT 0,
  closed_at DATETIME NULL,
  close_reason VARCHAR(32) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_orders_order_no (order_no),
  KEY idx_orders_user_created (user_id, created_at),
  KEY idx_orders_status_created (order_status, created_at),
  KEY idx_orders_review_due (review_status, review_due_at),
  KEY idx_orders_pay_status_created (payment_status, created_at),
  KEY idx_orders_shipping_status_shipped (shipping_status, shipped_at),
  KEY idx_orders_refund_due (refund_status, refund_due_at),
  KEY idx_orders_source_review (order_source, review_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  operator_type VARCHAR(16) NOT NULL,
  operator_id BIGINT NOT NULL DEFAULT 0,
  payload JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_order_events_order_created (order_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
