// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: admin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminRpc_AdminLogin_FullMethodName         = "/admin.AdminRpc/AdminLogin"
	AdminRpc_AdminRefreshToken_FullMethodName  = "/admin.AdminRpc/AdminRefreshToken"
	AdminRpc_AdminLogout_FullMethodName        = "/admin.AdminRpc/AdminLogout"
	AdminRpc_GetMyAdminProfile_FullMethodName  = "/admin.AdminRpc/GetMyAdminProfile"
	AdminRpc_ChangeMyPassword_FullMethodName   = "/admin.AdminRpc/ChangeMyPassword"
	AdminRpc_CreateAdmin_FullMethodName        = "/admin.AdminRpc/CreateAdmin"
	AdminRpc_UpdateAdmin_FullMethodName        = "/admin.AdminRpc/UpdateAdmin"
	AdminRpc_SetAdminStatus_FullMethodName     = "/admin.AdminRpc/SetAdminStatus"
	AdminRpc_ResetAdminPassword_FullMethodName = "/admin.AdminRpc/ResetAdminPassword"
	AdminRpc_DeleteAdmin_FullMethodName        = "/admin.AdminRpc/DeleteAdmin"
	AdminRpc_GetAdmin_FullMethodName           = "/admin.AdminRpc/GetAdmin"
	AdminRpc_ListAdmins_FullMethodName         = "/admin.AdminRpc/ListAdmins"
	AdminRpc_BindAdminRoles_FullMethodName     = "/admin.AdminRpc/BindAdminRoles"
	AdminRpc_CreateRole_FullMethodName         = "/admin.AdminRpc/CreateRole"
	AdminRpc_UpdateRole_FullMethodName         = "/admin.AdminRpc/UpdateRole"
	AdminRpc_DeleteRole_FullMethodName         = "/admin.AdminRpc/DeleteRole"
	AdminRpc_GetRole_FullMethodName            = "/admin.AdminRpc/GetRole"
	AdminRpc_ListRoles_FullMethodName          = "/admin.AdminRpc/ListRoles"
	AdminRpc_SetRoleDomains_FullMethodName     = "/admin.AdminRpc/SetRoleDomains"
	AdminRpc_ListAdminAuditLogs_FullMethodName = "/admin.AdminRpc/ListAdminAuditLogs"
)

// AdminRpcClient is the client API for AdminRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminRpcClient interface {
	AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminAuthResp, error)
	AdminRefreshToken(ctx context.Context, in *AdminRefreshTokenReq, opts ...grpc.CallOption) (*AdminAuthResp, error)
	AdminLogout(ctx context.Context, in *AdminLogoutReq, opts ...grpc.CallOption) (*AdminLogoutResp, error)
	GetMyAdminProfile(ctx context.Context, in *GetMyAdminProfileReq, opts ...grpc.CallOption) (*GetMyAdminProfileResp, error)
	ChangeMyPassword(ctx context.Context, in *ChangeMyPasswordReq, opts ...grpc.CallOption) (*ChangeMyPasswordResp, error)
	CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*CreateAdminResp, error)
	UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*UpdateAdminResp, error)
	SetAdminStatus(ctx context.Context, in *SetAdminStatusReq, opts ...grpc.CallOption) (*SetAdminStatusResp, error)
	ResetAdminPassword(ctx context.Context, in *ResetAdminPasswordReq, opts ...grpc.CallOption) (*ResetAdminPasswordResp, error)
	DeleteAdmin(ctx context.Context, in *DeleteAdminReq, opts ...grpc.CallOption) (*DeleteAdminResp, error)
	GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*GetAdminResp, error)
	ListAdmins(ctx context.Context, in *ListAdminsReq, opts ...grpc.CallOption) (*ListAdminsResp, error)
	BindAdminRoles(ctx context.Context, in *BindAdminRolesReq, opts ...grpc.CallOption) (*BindAdminRolesResp, error)
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
	DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error)
	GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*GetRoleResp, error)
	ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error)
	SetRoleDomains(ctx context.Context, in *SetRoleDomainsReq, opts ...grpc.CallOption) (*SetRoleDomainsResp, error)
	ListAdminAuditLogs(ctx context.Context, in *ListAdminAuditLogsReq, opts ...grpc.CallOption) (*ListAdminAuditLogsResp, error)
}

type adminRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminRpcClient(cc grpc.ClientConnInterface) AdminRpcClient {
	return &adminRpcClient{cc}
}

func (c *adminRpcClient) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAuthResp)
	err := c.cc.Invoke(ctx, AdminRpc_AdminLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) AdminRefreshToken(ctx context.Context, in *AdminRefreshTokenReq, opts ...grpc.CallOption) (*AdminAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAuthResp)
	err := c.cc.Invoke(ctx, AdminRpc_AdminRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) AdminLogout(ctx context.Context, in *AdminLogoutReq, opts ...grpc.CallOption) (*AdminLogoutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminLogoutResp)
	err := c.cc.Invoke(ctx, AdminRpc_AdminLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) GetMyAdminProfile(ctx context.Context, in *GetMyAdminProfileReq, opts ...grpc.CallOption) (*GetMyAdminProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyAdminProfileResp)
	err := c.cc.Invoke(ctx, AdminRpc_GetMyAdminProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) ChangeMyPassword(ctx context.Context, in *ChangeMyPasswordReq, opts ...grpc.CallOption) (*ChangeMyPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeMyPasswordResp)
	err := c.cc.Invoke(ctx, AdminRpc_ChangeMyPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) CreateAdmin(ctx context.Context, in *CreateAdminReq, opts ...grpc.CallOption) (*CreateAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdminResp)
	err := c.cc.Invoke(ctx, AdminRpc_CreateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) UpdateAdmin(ctx context.Context, in *UpdateAdminReq, opts ...grpc.CallOption) (*UpdateAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminResp)
	err := c.cc.Invoke(ctx, AdminRpc_UpdateAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) SetAdminStatus(ctx context.Context, in *SetAdminStatusReq, opts ...grpc.CallOption) (*SetAdminStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdminStatusResp)
	err := c.cc.Invoke(ctx, AdminRpc_SetAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) ResetAdminPassword(ctx context.Context, in *ResetAdminPasswordReq, opts ...grpc.CallOption) (*ResetAdminPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetAdminPasswordResp)
	err := c.cc.Invoke(ctx, AdminRpc_ResetAdminPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) DeleteAdmin(ctx context.Context, in *DeleteAdminReq, opts ...grpc.CallOption) (*DeleteAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdminResp)
	err := c.cc.Invoke(ctx, AdminRpc_DeleteAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) GetAdmin(ctx context.Context, in *GetAdminReq, opts ...grpc.CallOption) (*GetAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminResp)
	err := c.cc.Invoke(ctx, AdminRpc_GetAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) ListAdmins(ctx context.Context, in *ListAdminsReq, opts ...grpc.CallOption) (*ListAdminsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminsResp)
	err := c.cc.Invoke(ctx, AdminRpc_ListAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) BindAdminRoles(ctx context.Context, in *BindAdminRolesReq, opts ...grpc.CallOption) (*BindAdminRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindAdminRolesResp)
	err := c.cc.Invoke(ctx, AdminRpc_BindAdminRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleResp)
	err := c.cc.Invoke(ctx, AdminRpc_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoleResp)
	err := c.cc.Invoke(ctx, AdminRpc_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleResp)
	err := c.cc.Invoke(ctx, AdminRpc_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) GetRole(ctx context.Context, in *GetRoleReq, opts ...grpc.CallOption) (*GetRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleResp)
	err := c.cc.Invoke(ctx, AdminRpc_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResp)
	err := c.cc.Invoke(ctx, AdminRpc_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) SetRoleDomains(ctx context.Context, in *SetRoleDomainsReq, opts ...grpc.CallOption) (*SetRoleDomainsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoleDomainsResp)
	err := c.cc.Invoke(ctx, AdminRpc_SetRoleDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRpcClient) ListAdminAuditLogs(ctx context.Context, in *ListAdminAuditLogsReq, opts ...grpc.CallOption) (*ListAdminAuditLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminAuditLogsResp)
	err := c.cc.Invoke(ctx, AdminRpc_ListAdminAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRpcServer is the server API for AdminRpc service.
// All implementations must embed UnimplementedAdminRpcServer
// for forward compatibility.
type AdminRpcServer interface {
	AdminLogin(context.Context, *AdminLoginReq) (*AdminAuthResp, error)
	AdminRefreshToken(context.Context, *AdminRefreshTokenReq) (*AdminAuthResp, error)
	AdminLogout(context.Context, *AdminLogoutReq) (*AdminLogoutResp, error)
	GetMyAdminProfile(context.Context, *GetMyAdminProfileReq) (*GetMyAdminProfileResp, error)
	ChangeMyPassword(context.Context, *ChangeMyPasswordReq) (*ChangeMyPasswordResp, error)
	CreateAdmin(context.Context, *CreateAdminReq) (*CreateAdminResp, error)
	UpdateAdmin(context.Context, *UpdateAdminReq) (*UpdateAdminResp, error)
	SetAdminStatus(context.Context, *SetAdminStatusReq) (*SetAdminStatusResp, error)
	ResetAdminPassword(context.Context, *ResetAdminPasswordReq) (*ResetAdminPasswordResp, error)
	DeleteAdmin(context.Context, *DeleteAdminReq) (*DeleteAdminResp, error)
	GetAdmin(context.Context, *GetAdminReq) (*GetAdminResp, error)
	ListAdmins(context.Context, *ListAdminsReq) (*ListAdminsResp, error)
	BindAdminRoles(context.Context, *BindAdminRolesReq) (*BindAdminRolesResp, error)
	CreateRole(context.Context, *CreateRoleReq) (*CreateRoleResp, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error)
	DeleteRole(context.Context, *DeleteRoleReq) (*DeleteRoleResp, error)
	GetRole(context.Context, *GetRoleReq) (*GetRoleResp, error)
	ListRoles(context.Context, *ListRolesReq) (*ListRolesResp, error)
	SetRoleDomains(context.Context, *SetRoleDomainsReq) (*SetRoleDomainsResp, error)
	ListAdminAuditLogs(context.Context, *ListAdminAuditLogsReq) (*ListAdminAuditLogsResp, error)
	mustEmbedUnimplementedAdminRpcServer()
}

// UnimplementedAdminRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminRpcServer struct{}

func (UnimplementedAdminRpcServer) AdminLogin(context.Context, *AdminLoginReq) (*AdminAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAdminRpcServer) AdminRefreshToken(context.Context, *AdminRefreshTokenReq) (*AdminAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminRefreshToken not implemented")
}
func (UnimplementedAdminRpcServer) AdminLogout(context.Context, *AdminLogoutReq) (*AdminLogoutResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminLogout not implemented")
}
func (UnimplementedAdminRpcServer) GetMyAdminProfile(context.Context, *GetMyAdminProfileReq) (*GetMyAdminProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyAdminProfile not implemented")
}
func (UnimplementedAdminRpcServer) ChangeMyPassword(context.Context, *ChangeMyPasswordReq) (*ChangeMyPasswordResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMyPassword not implemented")
}
func (UnimplementedAdminRpcServer) CreateAdmin(context.Context, *CreateAdminReq) (*CreateAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdmin not implemented")
}
func (UnimplementedAdminRpcServer) UpdateAdmin(context.Context, *UpdateAdminReq) (*UpdateAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdmin not implemented")
}
func (UnimplementedAdminRpcServer) SetAdminStatus(context.Context, *SetAdminStatusReq) (*SetAdminStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAdminStatus not implemented")
}
func (UnimplementedAdminRpcServer) ResetAdminPassword(context.Context, *ResetAdminPasswordReq) (*ResetAdminPasswordResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetAdminPassword not implemented")
}
func (UnimplementedAdminRpcServer) DeleteAdmin(context.Context, *DeleteAdminReq) (*DeleteAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdmin not implemented")
}
func (UnimplementedAdminRpcServer) GetAdmin(context.Context, *GetAdminReq) (*GetAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdmin not implemented")
}
func (UnimplementedAdminRpcServer) ListAdmins(context.Context, *ListAdminsReq) (*ListAdminsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdmins not implemented")
}
func (UnimplementedAdminRpcServer) BindAdminRoles(context.Context, *BindAdminRolesReq) (*BindAdminRolesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindAdminRoles not implemented")
}
func (UnimplementedAdminRpcServer) CreateRole(context.Context, *CreateRoleReq) (*CreateRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedAdminRpcServer) UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedAdminRpcServer) DeleteRole(context.Context, *DeleteRoleReq) (*DeleteRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedAdminRpcServer) GetRole(context.Context, *GetRoleReq) (*GetRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedAdminRpcServer) ListRoles(context.Context, *ListRolesReq) (*ListRolesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedAdminRpcServer) SetRoleDomains(context.Context, *SetRoleDomainsReq) (*SetRoleDomainsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRoleDomains not implemented")
}
func (UnimplementedAdminRpcServer) ListAdminAuditLogs(context.Context, *ListAdminAuditLogsReq) (*ListAdminAuditLogsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminAuditLogs not implemented")
}
func (UnimplementedAdminRpcServer) mustEmbedUnimplementedAdminRpcServer() {}
func (UnimplementedAdminRpcServer) testEmbeddedByValue()                  {}

// UnsafeAdminRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminRpcServer will
// result in compilation errors.
type UnsafeAdminRpcServer interface {
	mustEmbedUnimplementedAdminRpcServer()
}

func RegisterAdminRpcServer(s grpc.ServiceRegistrar, srv AdminRpcServer) {
	// If the following call panics, it indicates UnimplementedAdminRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminRpc_ServiceDesc, srv)
}

func _AdminRpc_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).AdminLogin(ctx, req.(*AdminLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_AdminRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).AdminRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_AdminRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).AdminRefreshToken(ctx, req.(*AdminRefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_AdminLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).AdminLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_AdminLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).AdminLogout(ctx, req.(*AdminLogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_GetMyAdminProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyAdminProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).GetMyAdminProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_GetMyAdminProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).GetMyAdminProfile(ctx, req.(*GetMyAdminProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_ChangeMyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMyPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).ChangeMyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_ChangeMyPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).ChangeMyPassword(ctx, req.(*ChangeMyPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_CreateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).CreateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_CreateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).CreateAdmin(ctx, req.(*CreateAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_UpdateAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).UpdateAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_UpdateAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).UpdateAdmin(ctx, req.(*UpdateAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_SetAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdminStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).SetAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_SetAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).SetAdminStatus(ctx, req.(*SetAdminStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_ResetAdminPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetAdminPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).ResetAdminPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_ResetAdminPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).ResetAdminPassword(ctx, req.(*ResetAdminPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_DeleteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).DeleteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_DeleteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).DeleteAdmin(ctx, req.(*DeleteAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_GetAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).GetAdmin(ctx, req.(*GetAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_ListAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).ListAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_ListAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).ListAdmins(ctx, req.(*ListAdminsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_BindAdminRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAdminRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).BindAdminRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_BindAdminRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).BindAdminRoles(ctx, req.(*BindAdminRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).DeleteRole(ctx, req.(*DeleteRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).GetRole(ctx, req.(*GetRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).ListRoles(ctx, req.(*ListRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_SetRoleDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleDomainsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).SetRoleDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_SetRoleDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).SetRoleDomains(ctx, req.(*SetRoleDomainsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRpc_ListAdminAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminAuditLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRpcServer).ListAdminAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminRpc_ListAdminAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRpcServer).ListAdminAuditLogs(ctx, req.(*ListAdminAuditLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminRpc_ServiceDesc is the grpc.ServiceDesc for AdminRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminRpc",
	HandlerType: (*AdminRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _AdminRpc_AdminLogin_Handler,
		},
		{
			MethodName: "AdminRefreshToken",
			Handler:    _AdminRpc_AdminRefreshToken_Handler,
		},
		{
			MethodName: "AdminLogout",
			Handler:    _AdminRpc_AdminLogout_Handler,
		},
		{
			MethodName: "GetMyAdminProfile",
			Handler:    _AdminRpc_GetMyAdminProfile_Handler,
		},
		{
			MethodName: "ChangeMyPassword",
			Handler:    _AdminRpc_ChangeMyPassword_Handler,
		},
		{
			MethodName: "CreateAdmin",
			Handler:    _AdminRpc_CreateAdmin_Handler,
		},
		{
			MethodName: "UpdateAdmin",
			Handler:    _AdminRpc_UpdateAdmin_Handler,
		},
		{
			MethodName: "SetAdminStatus",
			Handler:    _AdminRpc_SetAdminStatus_Handler,
		},
		{
			MethodName: "ResetAdminPassword",
			Handler:    _AdminRpc_ResetAdminPassword_Handler,
		},
		{
			MethodName: "DeleteAdmin",
			Handler:    _AdminRpc_DeleteAdmin_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _AdminRpc_GetAdmin_Handler,
		},
		{
			MethodName: "ListAdmins",
			Handler:    _AdminRpc_ListAdmins_Handler,
		},
		{
			MethodName: "BindAdminRoles",
			Handler:    _AdminRpc_BindAdminRoles_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _AdminRpc_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _AdminRpc_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _AdminRpc_DeleteRole_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _AdminRpc_GetRole_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _AdminRpc_ListRoles_Handler,
		},
		{
			MethodName: "SetRoleDomains",
			Handler:    _AdminRpc_SetRoleDomains_Handler,
		},
		{
			MethodName: "ListAdminAuditLogs",
			Handler:    _AdminRpc_ListAdminAuditLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
