// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: apps/seckill/rpc/seckill.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeckillRpc_CreateActivity_FullMethodName       = "/seckill.SeckillRpc/CreateActivity"
	SeckillRpc_UpdateActivity_FullMethodName       = "/seckill.SeckillRpc/UpdateActivity"
	SeckillRpc_DeleteActivity_FullMethodName       = "/seckill.SeckillRpc/DeleteActivity"
	SeckillRpc_GetActivityAdmin_FullMethodName     = "/seckill.SeckillRpc/GetActivityAdmin"
	SeckillRpc_ListActivitiesAdmin_FullMethodName  = "/seckill.SeckillRpc/ListActivitiesAdmin"
	SeckillRpc_UpsertActivityItem_FullMethodName   = "/seckill.SeckillRpc/UpsertActivityItem"
	SeckillRpc_RemoveActivityItem_FullMethodName   = "/seckill.SeckillRpc/RemoveActivityItem"
	SeckillRpc_PublishActivity_FullMethodName      = "/seckill.SeckillRpc/PublishActivity"
	SeckillRpc_OfflineActivity_FullMethodName      = "/seckill.SeckillRpc/OfflineActivity"
	SeckillRpc_GetActivityTraffic_FullMethodName   = "/seckill.SeckillRpc/GetActivityTraffic"
	SeckillRpc_ListActivityOrders_FullMethodName   = "/seckill.SeckillRpc/ListActivityOrders"
	SeckillRpc_ListActivitiesPublic_FullMethodName = "/seckill.SeckillRpc/ListActivitiesPublic"
	SeckillRpc_GetActivityPublic_FullMethodName    = "/seckill.SeckillRpc/GetActivityPublic"
	SeckillRpc_Purchase_FullMethodName             = "/seckill.SeckillRpc/Purchase"
	SeckillRpc_TrackEvent_FullMethodName           = "/seckill.SeckillRpc/TrackEvent"
)

// SeckillRpcClient is the client API for SeckillRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeckillRpcClient interface {
	// 管理侧接口
	CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error)
	UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*UpdateActivityResp, error)
	DeleteActivity(ctx context.Context, in *DeleteActivityReq, opts ...grpc.CallOption) (*DeleteActivityResp, error)
	GetActivityAdmin(ctx context.Context, in *GetActivityAdminReq, opts ...grpc.CallOption) (*GetActivityAdminResp, error)
	ListActivitiesAdmin(ctx context.Context, in *ListActivitiesAdminReq, opts ...grpc.CallOption) (*ListActivitiesAdminResp, error)
	UpsertActivityItem(ctx context.Context, in *UpsertActivityItemReq, opts ...grpc.CallOption) (*UpsertActivityItemResp, error)
	RemoveActivityItem(ctx context.Context, in *RemoveActivityItemReq, opts ...grpc.CallOption) (*RemoveActivityItemResp, error)
	PublishActivity(ctx context.Context, in *PublishActivityReq, opts ...grpc.CallOption) (*PublishActivityResp, error)
	OfflineActivity(ctx context.Context, in *OfflineActivityReq, opts ...grpc.CallOption) (*OfflineActivityResp, error)
	GetActivityTraffic(ctx context.Context, in *GetActivityTrafficReq, opts ...grpc.CallOption) (*GetActivityTrafficResp, error)
	ListActivityOrders(ctx context.Context, in *ListActivityOrdersReq, opts ...grpc.CallOption) (*ListActivityOrdersResp, error)
	// 用户侧接口
	ListActivitiesPublic(ctx context.Context, in *ListActivitiesPublicReq, opts ...grpc.CallOption) (*ListActivitiesPublicResp, error)
	GetActivityPublic(ctx context.Context, in *GetActivityPublicReq, opts ...grpc.CallOption) (*GetActivityPublicResp, error)
	Purchase(ctx context.Context, in *PurchaseReq, opts ...grpc.CallOption) (*PurchaseResp, error)
	TrackEvent(ctx context.Context, in *TrackEventReq, opts ...grpc.CallOption) (*TrackEventResp, error)
}

type seckillRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillRpcClient(cc grpc.ClientConnInterface) SeckillRpcClient {
	return &seckillRpcClient{cc}
}

func (c *seckillRpcClient) CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateActivityResp)
	err := c.cc.Invoke(ctx, SeckillRpc_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*UpdateActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateActivityResp)
	err := c.cc.Invoke(ctx, SeckillRpc_UpdateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) DeleteActivity(ctx context.Context, in *DeleteActivityReq, opts ...grpc.CallOption) (*DeleteActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteActivityResp)
	err := c.cc.Invoke(ctx, SeckillRpc_DeleteActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) GetActivityAdmin(ctx context.Context, in *GetActivityAdminReq, opts ...grpc.CallOption) (*GetActivityAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivityAdminResp)
	err := c.cc.Invoke(ctx, SeckillRpc_GetActivityAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) ListActivitiesAdmin(ctx context.Context, in *ListActivitiesAdminReq, opts ...grpc.CallOption) (*ListActivitiesAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesAdminResp)
	err := c.cc.Invoke(ctx, SeckillRpc_ListActivitiesAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) UpsertActivityItem(ctx context.Context, in *UpsertActivityItemReq, opts ...grpc.CallOption) (*UpsertActivityItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertActivityItemResp)
	err := c.cc.Invoke(ctx, SeckillRpc_UpsertActivityItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) RemoveActivityItem(ctx context.Context, in *RemoveActivityItemReq, opts ...grpc.CallOption) (*RemoveActivityItemResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveActivityItemResp)
	err := c.cc.Invoke(ctx, SeckillRpc_RemoveActivityItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) PublishActivity(ctx context.Context, in *PublishActivityReq, opts ...grpc.CallOption) (*PublishActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishActivityResp)
	err := c.cc.Invoke(ctx, SeckillRpc_PublishActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) OfflineActivity(ctx context.Context, in *OfflineActivityReq, opts ...grpc.CallOption) (*OfflineActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfflineActivityResp)
	err := c.cc.Invoke(ctx, SeckillRpc_OfflineActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) GetActivityTraffic(ctx context.Context, in *GetActivityTrafficReq, opts ...grpc.CallOption) (*GetActivityTrafficResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivityTrafficResp)
	err := c.cc.Invoke(ctx, SeckillRpc_GetActivityTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) ListActivityOrders(ctx context.Context, in *ListActivityOrdersReq, opts ...grpc.CallOption) (*ListActivityOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivityOrdersResp)
	err := c.cc.Invoke(ctx, SeckillRpc_ListActivityOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) ListActivitiesPublic(ctx context.Context, in *ListActivitiesPublicReq, opts ...grpc.CallOption) (*ListActivitiesPublicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesPublicResp)
	err := c.cc.Invoke(ctx, SeckillRpc_ListActivitiesPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) GetActivityPublic(ctx context.Context, in *GetActivityPublicReq, opts ...grpc.CallOption) (*GetActivityPublicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActivityPublicResp)
	err := c.cc.Invoke(ctx, SeckillRpc_GetActivityPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) Purchase(ctx context.Context, in *PurchaseReq, opts ...grpc.CallOption) (*PurchaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseResp)
	err := c.cc.Invoke(ctx, SeckillRpc_Purchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillRpcClient) TrackEvent(ctx context.Context, in *TrackEventReq, opts ...grpc.CallOption) (*TrackEventResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackEventResp)
	err := c.cc.Invoke(ctx, SeckillRpc_TrackEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillRpcServer is the server API for SeckillRpc service.
// All implementations must embed UnimplementedSeckillRpcServer
// for forward compatibility.
type SeckillRpcServer interface {
	// 管理侧接口
	CreateActivity(context.Context, *CreateActivityReq) (*CreateActivityResp, error)
	UpdateActivity(context.Context, *UpdateActivityReq) (*UpdateActivityResp, error)
	DeleteActivity(context.Context, *DeleteActivityReq) (*DeleteActivityResp, error)
	GetActivityAdmin(context.Context, *GetActivityAdminReq) (*GetActivityAdminResp, error)
	ListActivitiesAdmin(context.Context, *ListActivitiesAdminReq) (*ListActivitiesAdminResp, error)
	UpsertActivityItem(context.Context, *UpsertActivityItemReq) (*UpsertActivityItemResp, error)
	RemoveActivityItem(context.Context, *RemoveActivityItemReq) (*RemoveActivityItemResp, error)
	PublishActivity(context.Context, *PublishActivityReq) (*PublishActivityResp, error)
	OfflineActivity(context.Context, *OfflineActivityReq) (*OfflineActivityResp, error)
	GetActivityTraffic(context.Context, *GetActivityTrafficReq) (*GetActivityTrafficResp, error)
	ListActivityOrders(context.Context, *ListActivityOrdersReq) (*ListActivityOrdersResp, error)
	// 用户侧接口
	ListActivitiesPublic(context.Context, *ListActivitiesPublicReq) (*ListActivitiesPublicResp, error)
	GetActivityPublic(context.Context, *GetActivityPublicReq) (*GetActivityPublicResp, error)
	Purchase(context.Context, *PurchaseReq) (*PurchaseResp, error)
	TrackEvent(context.Context, *TrackEventReq) (*TrackEventResp, error)
	mustEmbedUnimplementedSeckillRpcServer()
}

// UnimplementedSeckillRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeckillRpcServer struct{}

func (UnimplementedSeckillRpcServer) CreateActivity(context.Context, *CreateActivityReq) (*CreateActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedSeckillRpcServer) UpdateActivity(context.Context, *UpdateActivityReq) (*UpdateActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (UnimplementedSeckillRpcServer) DeleteActivity(context.Context, *DeleteActivityReq) (*DeleteActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActivity not implemented")
}
func (UnimplementedSeckillRpcServer) GetActivityAdmin(context.Context, *GetActivityAdminReq) (*GetActivityAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityAdmin not implemented")
}
func (UnimplementedSeckillRpcServer) ListActivitiesAdmin(context.Context, *ListActivitiesAdminReq) (*ListActivitiesAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivitiesAdmin not implemented")
}
func (UnimplementedSeckillRpcServer) UpsertActivityItem(context.Context, *UpsertActivityItemReq) (*UpsertActivityItemResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertActivityItem not implemented")
}
func (UnimplementedSeckillRpcServer) RemoveActivityItem(context.Context, *RemoveActivityItemReq) (*RemoveActivityItemResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveActivityItem not implemented")
}
func (UnimplementedSeckillRpcServer) PublishActivity(context.Context, *PublishActivityReq) (*PublishActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishActivity not implemented")
}
func (UnimplementedSeckillRpcServer) OfflineActivity(context.Context, *OfflineActivityReq) (*OfflineActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OfflineActivity not implemented")
}
func (UnimplementedSeckillRpcServer) GetActivityTraffic(context.Context, *GetActivityTrafficReq) (*GetActivityTrafficResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityTraffic not implemented")
}
func (UnimplementedSeckillRpcServer) ListActivityOrders(context.Context, *ListActivityOrdersReq) (*ListActivityOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivityOrders not implemented")
}
func (UnimplementedSeckillRpcServer) ListActivitiesPublic(context.Context, *ListActivitiesPublicReq) (*ListActivitiesPublicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivitiesPublic not implemented")
}
func (UnimplementedSeckillRpcServer) GetActivityPublic(context.Context, *GetActivityPublicReq) (*GetActivityPublicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityPublic not implemented")
}
func (UnimplementedSeckillRpcServer) Purchase(context.Context, *PurchaseReq) (*PurchaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Purchase not implemented")
}
func (UnimplementedSeckillRpcServer) TrackEvent(context.Context, *TrackEventReq) (*TrackEventResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackEvent not implemented")
}
func (UnimplementedSeckillRpcServer) mustEmbedUnimplementedSeckillRpcServer() {}
func (UnimplementedSeckillRpcServer) testEmbeddedByValue()                    {}

// UnsafeSeckillRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeckillRpcServer will
// result in compilation errors.
type UnsafeSeckillRpcServer interface {
	mustEmbedUnimplementedSeckillRpcServer()
}

func RegisterSeckillRpcServer(s grpc.ServiceRegistrar, srv SeckillRpcServer) {
	// If the following call panics, it indicates UnimplementedSeckillRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeckillRpc_ServiceDesc, srv)
}

func _SeckillRpc_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).CreateActivity(ctx, req.(*CreateActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_UpdateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).UpdateActivity(ctx, req.(*UpdateActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_DeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).DeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_DeleteActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).DeleteActivity(ctx, req.(*DeleteActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_GetActivityAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).GetActivityAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_GetActivityAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).GetActivityAdmin(ctx, req.(*GetActivityAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_ListActivitiesAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).ListActivitiesAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_ListActivitiesAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).ListActivitiesAdmin(ctx, req.(*ListActivitiesAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_UpsertActivityItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertActivityItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).UpsertActivityItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_UpsertActivityItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).UpsertActivityItem(ctx, req.(*UpsertActivityItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_RemoveActivityItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveActivityItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).RemoveActivityItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_RemoveActivityItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).RemoveActivityItem(ctx, req.(*RemoveActivityItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_PublishActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).PublishActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_PublishActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).PublishActivity(ctx, req.(*PublishActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_OfflineActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflineActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).OfflineActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_OfflineActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).OfflineActivity(ctx, req.(*OfflineActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_GetActivityTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityTrafficReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).GetActivityTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_GetActivityTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).GetActivityTraffic(ctx, req.(*GetActivityTrafficReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_ListActivityOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivityOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).ListActivityOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_ListActivityOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).ListActivityOrders(ctx, req.(*ListActivityOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_ListActivitiesPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).ListActivitiesPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_ListActivitiesPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).ListActivitiesPublic(ctx, req.(*ListActivitiesPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_GetActivityPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).GetActivityPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_GetActivityPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).GetActivityPublic(ctx, req.(*GetActivityPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_Purchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).Purchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_Purchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).Purchase(ctx, req.(*PurchaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillRpc_TrackEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillRpcServer).TrackEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeckillRpc_TrackEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillRpcServer).TrackEvent(ctx, req.(*TrackEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SeckillRpc_ServiceDesc is the grpc.ServiceDesc for SeckillRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeckillRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SeckillRpc",
	HandlerType: (*SeckillRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActivity",
			Handler:    _SeckillRpc_CreateActivity_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _SeckillRpc_UpdateActivity_Handler,
		},
		{
			MethodName: "DeleteActivity",
			Handler:    _SeckillRpc_DeleteActivity_Handler,
		},
		{
			MethodName: "GetActivityAdmin",
			Handler:    _SeckillRpc_GetActivityAdmin_Handler,
		},
		{
			MethodName: "ListActivitiesAdmin",
			Handler:    _SeckillRpc_ListActivitiesAdmin_Handler,
		},
		{
			MethodName: "UpsertActivityItem",
			Handler:    _SeckillRpc_UpsertActivityItem_Handler,
		},
		{
			MethodName: "RemoveActivityItem",
			Handler:    _SeckillRpc_RemoveActivityItem_Handler,
		},
		{
			MethodName: "PublishActivity",
			Handler:    _SeckillRpc_PublishActivity_Handler,
		},
		{
			MethodName: "OfflineActivity",
			Handler:    _SeckillRpc_OfflineActivity_Handler,
		},
		{
			MethodName: "GetActivityTraffic",
			Handler:    _SeckillRpc_GetActivityTraffic_Handler,
		},
		{
			MethodName: "ListActivityOrders",
			Handler:    _SeckillRpc_ListActivityOrders_Handler,
		},
		{
			MethodName: "ListActivitiesPublic",
			Handler:    _SeckillRpc_ListActivitiesPublic_Handler,
		},
		{
			MethodName: "GetActivityPublic",
			Handler:    _SeckillRpc_GetActivityPublic_Handler,
		},
		{
			MethodName: "Purchase",
			Handler:    _SeckillRpc_Purchase_Handler,
		},
		{
			MethodName: "TrackEvent",
			Handler:    _SeckillRpc_TrackEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/seckill/rpc/seckill.proto",
}
