// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: apps/seckill/rpc/seckill.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateActivityReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StyleConfigJson string                 `protobuf:"bytes,3,opt,name=style_config_json,json=styleConfigJson,proto3" json:"style_config_json,omitempty"`
	StartAtUnix     int64                  `protobuf:"varint,4,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix       int64                  `protobuf:"varint,5,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	AdminId         int64                  `protobuf:"varint,6,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateActivityReq) Reset() {
	*x = CreateActivityReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityReq) ProtoMessage() {}

func (x *CreateActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityReq.ProtoReflect.Descriptor instead.
func (*CreateActivityReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *CreateActivityReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateActivityReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityReq) GetStyleConfigJson() string {
	if x != nil {
		return x.StyleConfigJson
	}
	return ""
}

func (x *CreateActivityReq) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *CreateActivityReq) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

func (x *CreateActivityReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type CreateActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityAdmin         `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityResp) Reset() {
	*x = CreateActivityResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityResp) ProtoMessage() {}

func (x *CreateActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityResp.ProtoReflect.Descriptor instead.
func (*CreateActivityResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *CreateActivityResp) GetActivity() *ActivityAdmin {
	if x != nil {
		return x.Activity
	}
	return nil
}

type UpdateActivityReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivityId      int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StyleConfigJson string                 `protobuf:"bytes,4,opt,name=style_config_json,json=styleConfigJson,proto3" json:"style_config_json,omitempty"`
	StartAtUnix     int64                  `protobuf:"varint,5,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix       int64                  `protobuf:"varint,6,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	AdminId         int64                  `protobuf:"varint,7,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateActivityReq) Reset() {
	*x = UpdateActivityReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityReq) ProtoMessage() {}

func (x *UpdateActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityReq.ProtoReflect.Descriptor instead.
func (*UpdateActivityReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateActivityReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UpdateActivityReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateActivityReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateActivityReq) GetStyleConfigJson() string {
	if x != nil {
		return x.StyleConfigJson
	}
	return ""
}

func (x *UpdateActivityReq) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *UpdateActivityReq) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

func (x *UpdateActivityReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type UpdateActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityAdmin         `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityResp) Reset() {
	*x = UpdateActivityResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityResp) ProtoMessage() {}

func (x *UpdateActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityResp.ProtoReflect.Descriptor instead.
func (*UpdateActivityResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateActivityResp) GetActivity() *ActivityAdmin {
	if x != nil {
		return x.Activity
	}
	return nil
}

type DeleteActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityReq) Reset() {
	*x = DeleteActivityReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityReq) ProtoMessage() {}

func (x *DeleteActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityReq.ProtoReflect.Descriptor instead.
func (*DeleteActivityReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteActivityReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *DeleteActivityReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type DeleteActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityResp) Reset() {
	*x = DeleteActivityResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityResp) ProtoMessage() {}

func (x *DeleteActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityResp.ProtoReflect.Descriptor instead.
func (*DeleteActivityResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteActivityResp) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetActivityAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityAdminReq) Reset() {
	*x = GetActivityAdminReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityAdminReq) ProtoMessage() {}

func (x *GetActivityAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityAdminReq.ProtoReflect.Descriptor instead.
func (*GetActivityAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{6}
}

func (x *GetActivityAdminReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetActivityAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityAdmin         `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityAdminResp) Reset() {
	*x = GetActivityAdminResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityAdminResp) ProtoMessage() {}

func (x *GetActivityAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityAdminResp.ProtoReflect.Descriptor instead.
func (*GetActivityAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{7}
}

func (x *GetActivityAdminResp) GetActivity() *ActivityAdmin {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ListActivitiesAdminReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword        string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status         int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,5,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActivitiesAdminReq) Reset() {
	*x = ListActivitiesAdminReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesAdminReq) ProtoMessage() {}

func (x *ListActivitiesAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesAdminReq.ProtoReflect.Descriptor instead.
func (*ListActivitiesAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{8}
}

func (x *ListActivitiesAdminReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesAdminReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActivitiesAdminReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListActivitiesAdminReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListActivitiesAdminReq) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListActivitiesAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ActivityAdmin       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesAdminResp) Reset() {
	*x = ListActivitiesAdminResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesAdminResp) ProtoMessage() {}

func (x *ListActivitiesAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesAdminResp.ProtoReflect.Descriptor instead.
func (*ListActivitiesAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{9}
}

func (x *ListActivitiesAdminResp) GetList() []*ActivityAdmin {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListActivitiesAdminResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListActivitiesAdminResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesAdminResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpsertActivityItemReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActivityId         int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ItemId             int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProductId          int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SeckillPriceCent   int64                  `protobuf:"varint,4,opt,name=seckill_price_cent,json=seckillPriceCent,proto3" json:"seckill_price_cent,omitempty"`
	ReservedStockTotal int64                  `protobuf:"varint,5,opt,name=reserved_stock_total,json=reservedStockTotal,proto3" json:"reserved_stock_total,omitempty"`
	UserLimitMode      int32                  `protobuf:"varint,6,opt,name=user_limit_mode,json=userLimitMode,proto3" json:"user_limit_mode,omitempty"`
	UserLimitWindowSec int64                  `protobuf:"varint,7,opt,name=user_limit_window_sec,json=userLimitWindowSec,proto3" json:"user_limit_window_sec,omitempty"`
	UserLimitQty       int64                  `protobuf:"varint,8,opt,name=user_limit_qty,json=userLimitQty,proto3" json:"user_limit_qty,omitempty"`
	MaxQtyPerOrder     int64                  `protobuf:"varint,9,opt,name=max_qty_per_order,json=maxQtyPerOrder,proto3" json:"max_qty_per_order,omitempty"`
	Status             int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertActivityItemReq) Reset() {
	*x = UpsertActivityItemReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertActivityItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertActivityItemReq) ProtoMessage() {}

func (x *UpsertActivityItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertActivityItemReq.ProtoReflect.Descriptor instead.
func (*UpsertActivityItemReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertActivityItemReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UpsertActivityItemReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UpsertActivityItemReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpsertActivityItemReq) GetSeckillPriceCent() int64 {
	if x != nil {
		return x.SeckillPriceCent
	}
	return 0
}

func (x *UpsertActivityItemReq) GetReservedStockTotal() int64 {
	if x != nil {
		return x.ReservedStockTotal
	}
	return 0
}

func (x *UpsertActivityItemReq) GetUserLimitMode() int32 {
	if x != nil {
		return x.UserLimitMode
	}
	return 0
}

func (x *UpsertActivityItemReq) GetUserLimitWindowSec() int64 {
	if x != nil {
		return x.UserLimitWindowSec
	}
	return 0
}

func (x *UpsertActivityItemReq) GetUserLimitQty() int64 {
	if x != nil {
		return x.UserLimitQty
	}
	return 0
}

func (x *UpsertActivityItemReq) GetMaxQtyPerOrder() int64 {
	if x != nil {
		return x.MaxQtyPerOrder
	}
	return 0
}

func (x *UpsertActivityItemReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpsertActivityItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ActivityItemAdmin     `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertActivityItemResp) Reset() {
	*x = UpsertActivityItemResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertActivityItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertActivityItemResp) ProtoMessage() {}

func (x *UpsertActivityItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertActivityItemResp.ProtoReflect.Descriptor instead.
func (*UpsertActivityItemResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertActivityItemResp) GetItem() *ActivityItemAdmin {
	if x != nil {
		return x.Item
	}
	return nil
}

type RemoveActivityItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveActivityItemReq) Reset() {
	*x = RemoveActivityItemReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveActivityItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveActivityItemReq) ProtoMessage() {}

func (x *RemoveActivityItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveActivityItemReq.ProtoReflect.Descriptor instead.
func (*RemoveActivityItemReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveActivityItemReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *RemoveActivityItemReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RemoveActivityItemReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type RemoveActivityItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveActivityItemResp) Reset() {
	*x = RemoveActivityItemResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveActivityItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveActivityItemResp) ProtoMessage() {}

func (x *RemoveActivityItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveActivityItemResp.ProtoReflect.Descriptor instead.
func (*RemoveActivityItemResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveActivityItemResp) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *RemoveActivityItemResp) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type PublishActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishActivityReq) Reset() {
	*x = PublishActivityReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishActivityReq) ProtoMessage() {}

func (x *PublishActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishActivityReq.ProtoReflect.Descriptor instead.
func (*PublishActivityReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{14}
}

func (x *PublishActivityReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PublishActivityReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type PublishActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityAdmin         `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishActivityResp) Reset() {
	*x = PublishActivityResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishActivityResp) ProtoMessage() {}

func (x *PublishActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishActivityResp.ProtoReflect.Descriptor instead.
func (*PublishActivityResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{15}
}

func (x *PublishActivityResp) GetActivity() *ActivityAdmin {
	if x != nil {
		return x.Activity
	}
	return nil
}

type OfflineActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineActivityReq) Reset() {
	*x = OfflineActivityReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineActivityReq) ProtoMessage() {}

func (x *OfflineActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineActivityReq.ProtoReflect.Descriptor instead.
func (*OfflineActivityReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{16}
}

func (x *OfflineActivityReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OfflineActivityReq) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

type OfflineActivityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityAdmin         `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineActivityResp) Reset() {
	*x = OfflineActivityResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineActivityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineActivityResp) ProtoMessage() {}

func (x *OfflineActivityResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineActivityResp.ProtoReflect.Descriptor instead.
func (*OfflineActivityResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{17}
}

func (x *OfflineActivityResp) GetActivity() *ActivityAdmin {
	if x != nil {
		return x.Activity
	}
	return nil
}

type GetActivityTrafficReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActivityId     int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId int64                  `protobuf:"varint,2,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	FromMinuteUnix int64                  `protobuf:"varint,3,opt,name=from_minute_unix,json=fromMinuteUnix,proto3" json:"from_minute_unix,omitempty"`
	ToMinuteUnix   int64                  `protobuf:"varint,4,opt,name=to_minute_unix,json=toMinuteUnix,proto3" json:"to_minute_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetActivityTrafficReq) Reset() {
	*x = GetActivityTrafficReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityTrafficReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityTrafficReq) ProtoMessage() {}

func (x *GetActivityTrafficReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityTrafficReq.ProtoReflect.Descriptor instead.
func (*GetActivityTrafficReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{18}
}

func (x *GetActivityTrafficReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GetActivityTrafficReq) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *GetActivityTrafficReq) GetFromMinuteUnix() int64 {
	if x != nil {
		return x.FromMinuteUnix
	}
	return 0
}

func (x *GetActivityTrafficReq) GetToMinuteUnix() int64 {
	if x != nil {
		return x.ToMinuteUnix
	}
	return 0
}

type GetActivityTrafficResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*TrafficBucket       `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityTrafficResp) Reset() {
	*x = GetActivityTrafficResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityTrafficResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityTrafficResp) ProtoMessage() {}

func (x *GetActivityTrafficResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityTrafficResp.ProtoReflect.Descriptor instead.
func (*GetActivityTrafficResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{19}
}

func (x *GetActivityTrafficResp) GetRows() []*TrafficBucket {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ListActivityOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderStatus   int32                  `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus int32                  `protobuf:"varint,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	UserId        int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityOrdersReq) Reset() {
	*x = ListActivityOrdersReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityOrdersReq) ProtoMessage() {}

func (x *ListActivityOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityOrdersReq.ProtoReflect.Descriptor instead.
func (*ListActivityOrdersReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{20}
}

func (x *ListActivityOrdersReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ListActivityOrdersReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivityOrdersReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActivityOrdersReq) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *ListActivityOrdersReq) GetPaymentStatus() int32 {
	if x != nil {
		return x.PaymentStatus
	}
	return 0
}

func (x *ListActivityOrdersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListActivityOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ActivityOrderView   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityOrdersResp) Reset() {
	*x = ListActivityOrdersResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityOrdersResp) ProtoMessage() {}

func (x *ListActivityOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityOrdersResp.ProtoReflect.Descriptor instead.
func (*ListActivityOrdersResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{21}
}

func (x *ListActivityOrdersResp) GetList() []*ActivityOrderView {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListActivityOrdersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListActivityOrdersResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivityOrdersResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListActivitiesPublicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesPublicReq) Reset() {
	*x = ListActivitiesPublicReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesPublicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesPublicReq) ProtoMessage() {}

func (x *ListActivitiesPublicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesPublicReq.ProtoReflect.Descriptor instead.
func (*ListActivitiesPublicReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{22}
}

func (x *ListActivitiesPublicReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesPublicReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListActivitiesPublicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ActivityPublic      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesPublicResp) Reset() {
	*x = ListActivitiesPublicResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesPublicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesPublicResp) ProtoMessage() {}

func (x *ListActivitiesPublicResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesPublicResp.ProtoReflect.Descriptor instead.
func (*ListActivitiesPublicResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{23}
}

func (x *ListActivitiesPublicResp) GetList() []*ActivityPublic {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListActivitiesPublicResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListActivitiesPublicResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActivitiesPublicResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetActivityPublicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityPublicReq) Reset() {
	*x = GetActivityPublicReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityPublicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityPublicReq) ProtoMessage() {}

func (x *GetActivityPublicReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityPublicReq.ProtoReflect.Descriptor instead.
func (*GetActivityPublicReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{24}
}

func (x *GetActivityPublicReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetActivityPublicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *ActivityPublic        `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityPublicResp) Reset() {
	*x = GetActivityPublicResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityPublicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityPublicResp) ProtoMessage() {}

func (x *GetActivityPublicResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityPublicResp.ProtoReflect.Descriptor instead.
func (*GetActivityPublicResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{25}
}

func (x *GetActivityPublicResp) GetActivity() *ActivityPublic {
	if x != nil {
		return x.Activity
	}
	return nil
}

type PurchaseReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId     int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId int64                  `protobuf:"varint,3,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	Quantity       int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PurchaseReq) Reset() {
	*x = PurchaseReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseReq) ProtoMessage() {}

func (x *PurchaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseReq.ProtoReflect.Descriptor instead.
func (*PurchaseReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{26}
}

func (x *PurchaseReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PurchaseReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PurchaseReq) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *PurchaseReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PurchaseReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PurchaseResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActivityId     int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId int64                  `protobuf:"varint,2,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo        string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PurchaseResp) Reset() {
	*x = PurchaseResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResp) ProtoMessage() {}

func (x *PurchaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResp.ProtoReflect.Descriptor instead.
func (*PurchaseResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{27}
}

func (x *PurchaseResp) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PurchaseResp) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *PurchaseResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PurchaseResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type TrackEventReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActivityId     int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId int64                  `protobuf:"varint,2,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	UserId         int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId       string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,7,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackEventReq) Reset() {
	*x = TrackEventReq{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventReq) ProtoMessage() {}

func (x *TrackEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventReq.ProtoReflect.Descriptor instead.
func (*TrackEventReq) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{28}
}

func (x *TrackEventReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrackEventReq) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *TrackEventReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TrackEventReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackEventReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TrackEventReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TrackEventReq) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

type TrackEventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResp) Reset() {
	*x = TrackEventResp{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResp) ProtoMessage() {}

func (x *TrackEventResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResp.ProtoReflect.Descriptor instead.
func (*TrackEventResp) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{29}
}

func (x *TrackEventResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ActivityAdmin struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivityId      int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StyleConfigJson string                 `protobuf:"bytes,4,opt,name=style_config_json,json=styleConfigJson,proto3" json:"style_config_json,omitempty"`
	StartAtUnix     int64                  `protobuf:"varint,5,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix       int64                  `protobuf:"varint,6,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	Status          int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy       int64                  `protobuf:"varint,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy       int64                  `protobuf:"varint,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	CreatedAtUnix   int64                  `protobuf:"varint,10,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix   int64                  `protobuf:"varint,11,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	Items           []*ActivityItemAdmin   `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivityAdmin) Reset() {
	*x = ActivityAdmin{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAdmin) ProtoMessage() {}

func (x *ActivityAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAdmin.ProtoReflect.Descriptor instead.
func (*ActivityAdmin) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{30}
}

func (x *ActivityAdmin) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityAdmin) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityAdmin) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityAdmin) GetStyleConfigJson() string {
	if x != nil {
		return x.StyleConfigJson
	}
	return ""
}

func (x *ActivityAdmin) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *ActivityAdmin) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

func (x *ActivityAdmin) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityAdmin) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *ActivityAdmin) GetUpdatedBy() int64 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *ActivityAdmin) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ActivityAdmin) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *ActivityAdmin) GetItems() []*ActivityItemAdmin {
	if x != nil {
		return x.Items
	}
	return nil
}

type ActivityItemAdmin struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ItemId             int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ActivityId         int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ProductId          int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode            string                 `protobuf:"bytes,4,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	SnapshotName       string                 `protobuf:"bytes,5,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	SnapshotMainImage  string                 `protobuf:"bytes,6,opt,name=snapshot_main_image,json=snapshotMainImage,proto3" json:"snapshot_main_image,omitempty"`
	OriginPriceCent    int64                  `protobuf:"varint,7,opt,name=origin_price_cent,json=originPriceCent,proto3" json:"origin_price_cent,omitempty"`
	SeckillPriceCent   int64                  `protobuf:"varint,8,opt,name=seckill_price_cent,json=seckillPriceCent,proto3" json:"seckill_price_cent,omitempty"`
	ReservedStockTotal int64                  `protobuf:"varint,9,opt,name=reserved_stock_total,json=reservedStockTotal,proto3" json:"reserved_stock_total,omitempty"`
	AvailableStock     int64                  `protobuf:"varint,10,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	SoldStock          int64                  `protobuf:"varint,11,opt,name=sold_stock,json=soldStock,proto3" json:"sold_stock,omitempty"`
	UserLimitMode      int32                  `protobuf:"varint,12,opt,name=user_limit_mode,json=userLimitMode,proto3" json:"user_limit_mode,omitempty"`
	UserLimitWindowSec int64                  `protobuf:"varint,13,opt,name=user_limit_window_sec,json=userLimitWindowSec,proto3" json:"user_limit_window_sec,omitempty"`
	UserLimitQty       int64                  `protobuf:"varint,14,opt,name=user_limit_qty,json=userLimitQty,proto3" json:"user_limit_qty,omitempty"`
	MaxQtyPerOrder     int64                  `protobuf:"varint,15,opt,name=max_qty_per_order,json=maxQtyPerOrder,proto3" json:"max_qty_per_order,omitempty"`
	Status             int32                  `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAtUnix      int64                  `protobuf:"varint,17,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix      int64                  `protobuf:"varint,18,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActivityItemAdmin) Reset() {
	*x = ActivityItemAdmin{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityItemAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityItemAdmin) ProtoMessage() {}

func (x *ActivityItemAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityItemAdmin.ProtoReflect.Descriptor instead.
func (*ActivityItemAdmin) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{31}
}

func (x *ActivityItemAdmin) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ActivityItemAdmin) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityItemAdmin) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ActivityItemAdmin) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *ActivityItemAdmin) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

func (x *ActivityItemAdmin) GetSnapshotMainImage() string {
	if x != nil {
		return x.SnapshotMainImage
	}
	return ""
}

func (x *ActivityItemAdmin) GetOriginPriceCent() int64 {
	if x != nil {
		return x.OriginPriceCent
	}
	return 0
}

func (x *ActivityItemAdmin) GetSeckillPriceCent() int64 {
	if x != nil {
		return x.SeckillPriceCent
	}
	return 0
}

func (x *ActivityItemAdmin) GetReservedStockTotal() int64 {
	if x != nil {
		return x.ReservedStockTotal
	}
	return 0
}

func (x *ActivityItemAdmin) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

func (x *ActivityItemAdmin) GetSoldStock() int64 {
	if x != nil {
		return x.SoldStock
	}
	return 0
}

func (x *ActivityItemAdmin) GetUserLimitMode() int32 {
	if x != nil {
		return x.UserLimitMode
	}
	return 0
}

func (x *ActivityItemAdmin) GetUserLimitWindowSec() int64 {
	if x != nil {
		return x.UserLimitWindowSec
	}
	return 0
}

func (x *ActivityItemAdmin) GetUserLimitQty() int64 {
	if x != nil {
		return x.UserLimitQty
	}
	return 0
}

func (x *ActivityItemAdmin) GetMaxQtyPerOrder() int64 {
	if x != nil {
		return x.MaxQtyPerOrder
	}
	return 0
}

func (x *ActivityItemAdmin) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityItemAdmin) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ActivityItemAdmin) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type ActivityPublic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivityId      int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StyleConfigJson string                 `protobuf:"bytes,4,opt,name=style_config_json,json=styleConfigJson,proto3" json:"style_config_json,omitempty"`
	StartAtUnix     int64                  `protobuf:"varint,5,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix       int64                  `protobuf:"varint,6,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	Status          int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Items           []*ActivityItemPublic  `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivityPublic) Reset() {
	*x = ActivityPublic{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPublic) ProtoMessage() {}

func (x *ActivityPublic) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPublic.ProtoReflect.Descriptor instead.
func (*ActivityPublic) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{32}
}

func (x *ActivityPublic) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityPublic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActivityPublic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActivityPublic) GetStyleConfigJson() string {
	if x != nil {
		return x.StyleConfigJson
	}
	return ""
}

func (x *ActivityPublic) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *ActivityPublic) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

func (x *ActivityPublic) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityPublic) GetItems() []*ActivityItemPublic {
	if x != nil {
		return x.Items
	}
	return nil
}

type ActivityItemPublic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemId            int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProductId         int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode           string                 `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	SnapshotName      string                 `protobuf:"bytes,4,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	SnapshotMainImage string                 `protobuf:"bytes,5,opt,name=snapshot_main_image,json=snapshotMainImage,proto3" json:"snapshot_main_image,omitempty"`
	OriginPriceCent   int64                  `protobuf:"varint,6,opt,name=origin_price_cent,json=originPriceCent,proto3" json:"origin_price_cent,omitempty"`
	SeckillPriceCent  int64                  `protobuf:"varint,7,opt,name=seckill_price_cent,json=seckillPriceCent,proto3" json:"seckill_price_cent,omitempty"`
	InStock           bool                   `protobuf:"varint,8,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	MaxQtyPerOrder    int64                  `protobuf:"varint,9,opt,name=max_qty_per_order,json=maxQtyPerOrder,proto3" json:"max_qty_per_order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivityItemPublic) Reset() {
	*x = ActivityItemPublic{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityItemPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityItemPublic) ProtoMessage() {}

func (x *ActivityItemPublic) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityItemPublic.ProtoReflect.Descriptor instead.
func (*ActivityItemPublic) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{33}
}

func (x *ActivityItemPublic) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ActivityItemPublic) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ActivityItemPublic) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *ActivityItemPublic) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

func (x *ActivityItemPublic) GetSnapshotMainImage() string {
	if x != nil {
		return x.SnapshotMainImage
	}
	return ""
}

func (x *ActivityItemPublic) GetOriginPriceCent() int64 {
	if x != nil {
		return x.OriginPriceCent
	}
	return 0
}

func (x *ActivityItemPublic) GetSeckillPriceCent() int64 {
	if x != nil {
		return x.SeckillPriceCent
	}
	return 0
}

func (x *ActivityItemPublic) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ActivityItemPublic) GetMaxQtyPerOrder() int64 {
	if x != nil {
		return x.MaxQtyPerOrder
	}
	return 0
}

type TrafficBucket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BucketMinuteUnix int64                  `protobuf:"varint,1,opt,name=bucket_minute_unix,json=bucketMinuteUnix,proto3" json:"bucket_minute_unix,omitempty"`
	ActivityId       int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId   int64                  `protobuf:"varint,3,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	Pv               int64                  `protobuf:"varint,4,opt,name=pv,proto3" json:"pv,omitempty"`
	Uv               int64                  `protobuf:"varint,5,opt,name=uv,proto3" json:"uv,omitempty"`
	Click            int64                  `protobuf:"varint,6,opt,name=click,proto3" json:"click,omitempty"`
	PurchaseAttempt  int64                  `protobuf:"varint,7,opt,name=purchase_attempt,json=purchaseAttempt,proto3" json:"purchase_attempt,omitempty"`
	PurchaseSuccess  int64                  `protobuf:"varint,8,opt,name=purchase_success,json=purchaseSuccess,proto3" json:"purchase_success,omitempty"`
	PurchaseFail     int64                  `protobuf:"varint,9,opt,name=purchase_fail,json=purchaseFail,proto3" json:"purchase_fail,omitempty"`
	PaySuccess       int64                  `protobuf:"varint,10,opt,name=pay_success,json=paySuccess,proto3" json:"pay_success,omitempty"`
	OrderClosed      int64                  `protobuf:"varint,11,opt,name=order_closed,json=orderClosed,proto3" json:"order_closed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrafficBucket) Reset() {
	*x = TrafficBucket{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBucket) ProtoMessage() {}

func (x *TrafficBucket) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBucket.ProtoReflect.Descriptor instead.
func (*TrafficBucket) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{34}
}

func (x *TrafficBucket) GetBucketMinuteUnix() int64 {
	if x != nil {
		return x.BucketMinuteUnix
	}
	return 0
}

func (x *TrafficBucket) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *TrafficBucket) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *TrafficBucket) GetPv() int64 {
	if x != nil {
		return x.Pv
	}
	return 0
}

func (x *TrafficBucket) GetUv() int64 {
	if x != nil {
		return x.Uv
	}
	return 0
}

func (x *TrafficBucket) GetClick() int64 {
	if x != nil {
		return x.Click
	}
	return 0
}

func (x *TrafficBucket) GetPurchaseAttempt() int64 {
	if x != nil {
		return x.PurchaseAttempt
	}
	return 0
}

func (x *TrafficBucket) GetPurchaseSuccess() int64 {
	if x != nil {
		return x.PurchaseSuccess
	}
	return 0
}

func (x *TrafficBucket) GetPurchaseFail() int64 {
	if x != nil {
		return x.PurchaseFail
	}
	return 0
}

func (x *TrafficBucket) GetPaySuccess() int64 {
	if x != nil {
		return x.PaySuccess
	}
	return 0
}

func (x *TrafficBucket) GetOrderClosed() int64 {
	if x != nil {
		return x.OrderClosed
	}
	return 0
}

type ActivityOrderView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LinkId           int64                  `protobuf:"varint,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	OrderId          int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo          string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId           int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId       int64                  `protobuf:"varint,5,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityItemId   int64                  `protobuf:"varint,6,opt,name=activity_item_id,json=activityItemId,proto3" json:"activity_item_id,omitempty"`
	Quantity         int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderStatus      int32                  `protobuf:"varint,8,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus    int32                  `protobuf:"varint,9,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	CloseReason      string                 `protobuf:"bytes,10,opt,name=close_reason,json=closeReason,proto3" json:"close_reason,omitempty"`
	LastSyncedAtUnix int64                  `protobuf:"varint,11,opt,name=last_synced_at_unix,json=lastSyncedAtUnix,proto3" json:"last_synced_at_unix,omitempty"`
	CreatedAtUnix    int64                  `protobuf:"varint,12,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix    int64                  `protobuf:"varint,13,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActivityOrderView) Reset() {
	*x = ActivityOrderView{}
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityOrderView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityOrderView) ProtoMessage() {}

func (x *ActivityOrderView) ProtoReflect() protoreflect.Message {
	mi := &file_apps_seckill_rpc_seckill_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityOrderView.ProtoReflect.Descriptor instead.
func (*ActivityOrderView) Descriptor() ([]byte, []int) {
	return file_apps_seckill_rpc_seckill_proto_rawDescGZIP(), []int{35}
}

func (x *ActivityOrderView) GetLinkId() int64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

func (x *ActivityOrderView) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ActivityOrderView) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ActivityOrderView) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ActivityOrderView) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityOrderView) GetActivityItemId() int64 {
	if x != nil {
		return x.ActivityItemId
	}
	return 0
}

func (x *ActivityOrderView) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ActivityOrderView) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *ActivityOrderView) GetPaymentStatus() int32 {
	if x != nil {
		return x.PaymentStatus
	}
	return 0
}

func (x *ActivityOrderView) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *ActivityOrderView) GetLastSyncedAtUnix() int64 {
	if x != nil {
		return x.LastSyncedAtUnix
	}
	return 0
}

func (x *ActivityOrderView) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ActivityOrderView) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

var File_apps_seckill_rpc_seckill_proto protoreflect.FileDescriptor

const file_apps_seckill_rpc_seckill_proto_rawDesc = "" +
	"\n" +
	"\x1eapps/seckill/rpc/seckill.proto\x12\aseckill\"\xd6\x01\n" +
	"\x11CreateActivityReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11style_config_json\x18\x03 \x01(\tR\x0fstyleConfigJson\x12\"\n" +
	"\rstart_at_unix\x18\x04 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\x05 \x01(\x03R\tendAtUnix\x12\x19\n" +
	"\badmin_id\x18\x06 \x01(\x03R\aadminId\"H\n" +
	"\x12CreateActivityResp\x122\n" +
	"\bactivity\x18\x01 \x01(\v2\x16.seckill.ActivityAdminR\bactivity\"\xf7\x01\n" +
	"\x11UpdateActivityReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x11style_config_json\x18\x04 \x01(\tR\x0fstyleConfigJson\x12\"\n" +
	"\rstart_at_unix\x18\x05 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\x06 \x01(\x03R\tendAtUnix\x12\x19\n" +
	"\badmin_id\x18\a \x01(\x03R\aadminId\"H\n" +
	"\x12UpdateActivityResp\x122\n" +
	"\bactivity\x18\x01 \x01(\v2\x16.seckill.ActivityAdminR\bactivity\"O\n" +
	"\x11DeleteActivityReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\"5\n" +
	"\x12DeleteActivityResp\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\"6\n" +
	"\x13GetActivityAdminReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\"J\n" +
	"\x14GetActivityAdminResp\x122\n" +
	"\bactivity\x18\x01 \x01(\v2\x16.seckill.ActivityAdminR\bactivity\"\xa4\x01\n" +
	"\x16ListActivitiesAdminReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12'\n" +
	"\x0finclude_deleted\x18\x05 \x01(\bR\x0eincludeDeleted\"\x8c\x01\n" +
	"\x17ListActivitiesAdminResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.seckill.ActivityAdminR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\x94\x03\n" +
	"\x15UpsertActivityItemReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12,\n" +
	"\x12seckill_price_cent\x18\x04 \x01(\x03R\x10seckillPriceCent\x120\n" +
	"\x14reserved_stock_total\x18\x05 \x01(\x03R\x12reservedStockTotal\x12&\n" +
	"\x0fuser_limit_mode\x18\x06 \x01(\x05R\ruserLimitMode\x121\n" +
	"\x15user_limit_window_sec\x18\a \x01(\x03R\x12userLimitWindowSec\x12$\n" +
	"\x0euser_limit_qty\x18\b \x01(\x03R\fuserLimitQty\x12)\n" +
	"\x11max_qty_per_order\x18\t \x01(\x03R\x0emaxQtyPerOrder\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"H\n" +
	"\x16UpsertActivityItemResp\x12.\n" +
	"\x04item\x18\x01 \x01(\v2\x1a.seckill.ActivityItemAdminR\x04item\"l\n" +
	"\x15RemoveActivityItemReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\x03R\aadminId\"R\n" +
	"\x16RemoveActivityItemResp\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\"P\n" +
	"\x12PublishActivityReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\"I\n" +
	"\x13PublishActivityResp\x122\n" +
	"\bactivity\x18\x01 \x01(\v2\x16.seckill.ActivityAdminR\bactivity\"P\n" +
	"\x12OfflineActivityReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\"I\n" +
	"\x13OfflineActivityResp\x122\n" +
	"\bactivity\x18\x01 \x01(\v2\x16.seckill.ActivityAdminR\bactivity\"\xb2\x01\n" +
	"\x15GetActivityTrafficReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x02 \x01(\x03R\x0eactivityItemId\x12(\n" +
	"\x10from_minute_unix\x18\x03 \x01(\x03R\x0efromMinuteUnix\x12$\n" +
	"\x0eto_minute_unix\x18\x04 \x01(\x03R\ftoMinuteUnix\"D\n" +
	"\x16GetActivityTrafficResp\x12*\n" +
	"\x04rows\x18\x01 \x03(\v2\x16.seckill.TrafficBucketR\x04rows\"\xcc\x01\n" +
	"\x15ListActivityOrdersReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\x05R\rpaymentStatus\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId\"\x8f\x01\n" +
	"\x16ListActivityOrdersResp\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.seckill.ActivityOrderViewR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"J\n" +
	"\x17ListActivitiesPublicReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"\x8e\x01\n" +
	"\x18ListActivitiesPublicResp\x12+\n" +
	"\x04list\x18\x01 \x03(\v2\x17.seckill.ActivityPublicR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"7\n" +
	"\x14GetActivityPublicReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\"L\n" +
	"\x15GetActivityPublicResp\x123\n" +
	"\bactivity\x18\x01 \x01(\v2\x17.seckill.ActivityPublicR\bactivity\"\xb6\x01\n" +
	"\vPurchaseReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x03 \x01(\x03R\x0eactivityItemId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\x8f\x01\n" +
	"\fPurchaseResp\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x02 \x01(\x03R\x0eactivityItemId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\"\x82\x02\n" +
	"\rTrackEventReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x02 \x01(\x03R\x0eactivityItemId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12(\n" +
	"\x10occurred_at_unix\x18\a \x01(\x03R\x0eoccurredAtUnix\",\n" +
	"\x0eTrackEventResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xb0\x03\n" +
	"\rActivityAdmin\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x11style_config_json\x18\x04 \x01(\tR\x0fstyleConfigJson\x12\"\n" +
	"\rstart_at_unix\x18\x05 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\x06 \x01(\x03R\tendAtUnix\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\x03R\tupdatedBy\x12&\n" +
	"\x0fcreated_at_unix\x18\n" +
	" \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\v \x01(\x03R\rupdatedAtUnix\x120\n" +
	"\x05items\x18\f \x03(\v2\x1a.seckill.ActivityItemAdminR\x05items\"\xc4\x05\n" +
	"\x11ActivityItemAdmin\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x04 \x01(\tR\askuCode\x12#\n" +
	"\rsnapshot_name\x18\x05 \x01(\tR\fsnapshotName\x12.\n" +
	"\x13snapshot_main_image\x18\x06 \x01(\tR\x11snapshotMainImage\x12*\n" +
	"\x11origin_price_cent\x18\a \x01(\x03R\x0foriginPriceCent\x12,\n" +
	"\x12seckill_price_cent\x18\b \x01(\x03R\x10seckillPriceCent\x120\n" +
	"\x14reserved_stock_total\x18\t \x01(\x03R\x12reservedStockTotal\x12'\n" +
	"\x0favailable_stock\x18\n" +
	" \x01(\x03R\x0eavailableStock\x12\x1d\n" +
	"\n" +
	"sold_stock\x18\v \x01(\x03R\tsoldStock\x12&\n" +
	"\x0fuser_limit_mode\x18\f \x01(\x05R\ruserLimitMode\x121\n" +
	"\x15user_limit_window_sec\x18\r \x01(\x03R\x12userLimitWindowSec\x12$\n" +
	"\x0euser_limit_qty\x18\x0e \x01(\x03R\fuserLimitQty\x12)\n" +
	"\x11max_qty_per_order\x18\x0f \x01(\x03R\x0emaxQtyPerOrder\x12\x16\n" +
	"\x06status\x18\x10 \x01(\x05R\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\x11 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x12 \x01(\x03R\rupdatedAtUnix\"\xa4\x02\n" +
	"\x0eActivityPublic\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x11style_config_json\x18\x04 \x01(\tR\x0fstyleConfigJson\x12\"\n" +
	"\rstart_at_unix\x18\x05 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\x06 \x01(\x03R\tendAtUnix\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x121\n" +
	"\x05items\x18\b \x03(\v2\x1b.seckill.ActivityItemPublicR\x05items\"\xdc\x02\n" +
	"\x12ActivityItemPublic\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x03 \x01(\tR\askuCode\x12#\n" +
	"\rsnapshot_name\x18\x04 \x01(\tR\fsnapshotName\x12.\n" +
	"\x13snapshot_main_image\x18\x05 \x01(\tR\x11snapshotMainImage\x12*\n" +
	"\x11origin_price_cent\x18\x06 \x01(\x03R\x0foriginPriceCent\x12,\n" +
	"\x12seckill_price_cent\x18\a \x01(\x03R\x10seckillPriceCent\x12\x19\n" +
	"\bin_stock\x18\b \x01(\bR\ainStock\x12)\n" +
	"\x11max_qty_per_order\x18\t \x01(\x03R\x0emaxQtyPerOrder\"\xfd\x02\n" +
	"\rTrafficBucket\x12,\n" +
	"\x12bucket_minute_unix\x18\x01 \x01(\x03R\x10bucketMinuteUnix\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x03 \x01(\x03R\x0eactivityItemId\x12\x0e\n" +
	"\x02pv\x18\x04 \x01(\x03R\x02pv\x12\x0e\n" +
	"\x02uv\x18\x05 \x01(\x03R\x02uv\x12\x14\n" +
	"\x05click\x18\x06 \x01(\x03R\x05click\x12)\n" +
	"\x10purchase_attempt\x18\a \x01(\x03R\x0fpurchaseAttempt\x12)\n" +
	"\x10purchase_success\x18\b \x01(\x03R\x0fpurchaseSuccess\x12#\n" +
	"\rpurchase_fail\x18\t \x01(\x03R\fpurchaseFail\x12\x1f\n" +
	"\vpay_success\x18\n" +
	" \x01(\x03R\n" +
	"paySuccess\x12!\n" +
	"\forder_closed\x18\v \x01(\x03R\vorderClosed\"\xce\x03\n" +
	"\x11ActivityOrderView\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\x03R\x06linkId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x05 \x01(\x03R\n" +
	"activityId\x12(\n" +
	"\x10activity_item_id\x18\x06 \x01(\x03R\x0eactivityItemId\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12!\n" +
	"\forder_status\x18\b \x01(\x05R\vorderStatus\x12%\n" +
	"\x0epayment_status\x18\t \x01(\x05R\rpaymentStatus\x12!\n" +
	"\fclose_reason\x18\n" +
	" \x01(\tR\vcloseReason\x12-\n" +
	"\x13last_synced_at_unix\x18\v \x01(\x03R\x10lastSyncedAtUnix\x12&\n" +
	"\x0fcreated_at_unix\x18\f \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\r \x01(\x03R\rupdatedAtUnix2\xb9\t\n" +
	"\n" +
	"SeckillRpc\x12I\n" +
	"\x0eCreateActivity\x12\x1a.seckill.CreateActivityReq\x1a\x1b.seckill.CreateActivityResp\x12I\n" +
	"\x0eUpdateActivity\x12\x1a.seckill.UpdateActivityReq\x1a\x1b.seckill.UpdateActivityResp\x12I\n" +
	"\x0eDeleteActivity\x12\x1a.seckill.DeleteActivityReq\x1a\x1b.seckill.DeleteActivityResp\x12O\n" +
	"\x10GetActivityAdmin\x12\x1c.seckill.GetActivityAdminReq\x1a\x1d.seckill.GetActivityAdminResp\x12X\n" +
	"\x13ListActivitiesAdmin\x12\x1f.seckill.ListActivitiesAdminReq\x1a .seckill.ListActivitiesAdminResp\x12U\n" +
	"\x12UpsertActivityItem\x12\x1e.seckill.UpsertActivityItemReq\x1a\x1f.seckill.UpsertActivityItemResp\x12U\n" +
	"\x12RemoveActivityItem\x12\x1e.seckill.RemoveActivityItemReq\x1a\x1f.seckill.RemoveActivityItemResp\x12L\n" +
	"\x0fPublishActivity\x12\x1b.seckill.PublishActivityReq\x1a\x1c.seckill.PublishActivityResp\x12L\n" +
	"\x0fOfflineActivity\x12\x1b.seckill.OfflineActivityReq\x1a\x1c.seckill.OfflineActivityResp\x12U\n" +
	"\x12GetActivityTraffic\x12\x1e.seckill.GetActivityTrafficReq\x1a\x1f.seckill.GetActivityTrafficResp\x12U\n" +
	"\x12ListActivityOrders\x12\x1e.seckill.ListActivityOrdersReq\x1a\x1f.seckill.ListActivityOrdersResp\x12[\n" +
	"\x14ListActivitiesPublic\x12 .seckill.ListActivitiesPublicReq\x1a!.seckill.ListActivitiesPublicResp\x12R\n" +
	"\x11GetActivityPublic\x12\x1d.seckill.GetActivityPublicReq\x1a\x1e.seckill.GetActivityPublicResp\x127\n" +
	"\bPurchase\x12\x14.seckill.PurchaseReq\x1a\x15.seckill.PurchaseResp\x12=\n" +
	"\n" +
	"TrackEvent\x12\x16.seckill.TrackEventReq\x1a\x17.seckill.TrackEventRespB\"Z flashsale/apps/seckill/rpc/pb;pbb\x06proto3"

var (
	file_apps_seckill_rpc_seckill_proto_rawDescOnce sync.Once
	file_apps_seckill_rpc_seckill_proto_rawDescData []byte
)

func file_apps_seckill_rpc_seckill_proto_rawDescGZIP() []byte {
	file_apps_seckill_rpc_seckill_proto_rawDescOnce.Do(func() {
		file_apps_seckill_rpc_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_seckill_rpc_seckill_proto_rawDesc), len(file_apps_seckill_rpc_seckill_proto_rawDesc)))
	})
	return file_apps_seckill_rpc_seckill_proto_rawDescData
}

var file_apps_seckill_rpc_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_apps_seckill_rpc_seckill_proto_goTypes = []any{
	(*CreateActivityReq)(nil),        // 0: seckill.CreateActivityReq
	(*CreateActivityResp)(nil),       // 1: seckill.CreateActivityResp
	(*UpdateActivityReq)(nil),        // 2: seckill.UpdateActivityReq
	(*UpdateActivityResp)(nil),       // 3: seckill.UpdateActivityResp
	(*DeleteActivityReq)(nil),        // 4: seckill.DeleteActivityReq
	(*DeleteActivityResp)(nil),       // 5: seckill.DeleteActivityResp
	(*GetActivityAdminReq)(nil),      // 6: seckill.GetActivityAdminReq
	(*GetActivityAdminResp)(nil),     // 7: seckill.GetActivityAdminResp
	(*ListActivitiesAdminReq)(nil),   // 8: seckill.ListActivitiesAdminReq
	(*ListActivitiesAdminResp)(nil),  // 9: seckill.ListActivitiesAdminResp
	(*UpsertActivityItemReq)(nil),    // 10: seckill.UpsertActivityItemReq
	(*UpsertActivityItemResp)(nil),   // 11: seckill.UpsertActivityItemResp
	(*RemoveActivityItemReq)(nil),    // 12: seckill.RemoveActivityItemReq
	(*RemoveActivityItemResp)(nil),   // 13: seckill.RemoveActivityItemResp
	(*PublishActivityReq)(nil),       // 14: seckill.PublishActivityReq
	(*PublishActivityResp)(nil),      // 15: seckill.PublishActivityResp
	(*OfflineActivityReq)(nil),       // 16: seckill.OfflineActivityReq
	(*OfflineActivityResp)(nil),      // 17: seckill.OfflineActivityResp
	(*GetActivityTrafficReq)(nil),    // 18: seckill.GetActivityTrafficReq
	(*GetActivityTrafficResp)(nil),   // 19: seckill.GetActivityTrafficResp
	(*ListActivityOrdersReq)(nil),    // 20: seckill.ListActivityOrdersReq
	(*ListActivityOrdersResp)(nil),   // 21: seckill.ListActivityOrdersResp
	(*ListActivitiesPublicReq)(nil),  // 22: seckill.ListActivitiesPublicReq
	(*ListActivitiesPublicResp)(nil), // 23: seckill.ListActivitiesPublicResp
	(*GetActivityPublicReq)(nil),     // 24: seckill.GetActivityPublicReq
	(*GetActivityPublicResp)(nil),    // 25: seckill.GetActivityPublicResp
	(*PurchaseReq)(nil),              // 26: seckill.PurchaseReq
	(*PurchaseResp)(nil),             // 27: seckill.PurchaseResp
	(*TrackEventReq)(nil),            // 28: seckill.TrackEventReq
	(*TrackEventResp)(nil),           // 29: seckill.TrackEventResp
	(*ActivityAdmin)(nil),            // 30: seckill.ActivityAdmin
	(*ActivityItemAdmin)(nil),        // 31: seckill.ActivityItemAdmin
	(*ActivityPublic)(nil),           // 32: seckill.ActivityPublic
	(*ActivityItemPublic)(nil),       // 33: seckill.ActivityItemPublic
	(*TrafficBucket)(nil),            // 34: seckill.TrafficBucket
	(*ActivityOrderView)(nil),        // 35: seckill.ActivityOrderView
}
var file_apps_seckill_rpc_seckill_proto_depIdxs = []int32{
	30, // 0: seckill.CreateActivityResp.activity:type_name -> seckill.ActivityAdmin
	30, // 1: seckill.UpdateActivityResp.activity:type_name -> seckill.ActivityAdmin
	30, // 2: seckill.GetActivityAdminResp.activity:type_name -> seckill.ActivityAdmin
	30, // 3: seckill.ListActivitiesAdminResp.list:type_name -> seckill.ActivityAdmin
	31, // 4: seckill.UpsertActivityItemResp.item:type_name -> seckill.ActivityItemAdmin
	30, // 5: seckill.PublishActivityResp.activity:type_name -> seckill.ActivityAdmin
	30, // 6: seckill.OfflineActivityResp.activity:type_name -> seckill.ActivityAdmin
	34, // 7: seckill.GetActivityTrafficResp.rows:type_name -> seckill.TrafficBucket
	35, // 8: seckill.ListActivityOrdersResp.list:type_name -> seckill.ActivityOrderView
	32, // 9: seckill.ListActivitiesPublicResp.list:type_name -> seckill.ActivityPublic
	32, // 10: seckill.GetActivityPublicResp.activity:type_name -> seckill.ActivityPublic
	31, // 11: seckill.ActivityAdmin.items:type_name -> seckill.ActivityItemAdmin
	33, // 12: seckill.ActivityPublic.items:type_name -> seckill.ActivityItemPublic
	0,  // 13: seckill.SeckillRpc.CreateActivity:input_type -> seckill.CreateActivityReq
	2,  // 14: seckill.SeckillRpc.UpdateActivity:input_type -> seckill.UpdateActivityReq
	4,  // 15: seckill.SeckillRpc.DeleteActivity:input_type -> seckill.DeleteActivityReq
	6,  // 16: seckill.SeckillRpc.GetActivityAdmin:input_type -> seckill.GetActivityAdminReq
	8,  // 17: seckill.SeckillRpc.ListActivitiesAdmin:input_type -> seckill.ListActivitiesAdminReq
	10, // 18: seckill.SeckillRpc.UpsertActivityItem:input_type -> seckill.UpsertActivityItemReq
	12, // 19: seckill.SeckillRpc.RemoveActivityItem:input_type -> seckill.RemoveActivityItemReq
	14, // 20: seckill.SeckillRpc.PublishActivity:input_type -> seckill.PublishActivityReq
	16, // 21: seckill.SeckillRpc.OfflineActivity:input_type -> seckill.OfflineActivityReq
	18, // 22: seckill.SeckillRpc.GetActivityTraffic:input_type -> seckill.GetActivityTrafficReq
	20, // 23: seckill.SeckillRpc.ListActivityOrders:input_type -> seckill.ListActivityOrdersReq
	22, // 24: seckill.SeckillRpc.ListActivitiesPublic:input_type -> seckill.ListActivitiesPublicReq
	24, // 25: seckill.SeckillRpc.GetActivityPublic:input_type -> seckill.GetActivityPublicReq
	26, // 26: seckill.SeckillRpc.Purchase:input_type -> seckill.PurchaseReq
	28, // 27: seckill.SeckillRpc.TrackEvent:input_type -> seckill.TrackEventReq
	1,  // 28: seckill.SeckillRpc.CreateActivity:output_type -> seckill.CreateActivityResp
	3,  // 29: seckill.SeckillRpc.UpdateActivity:output_type -> seckill.UpdateActivityResp
	5,  // 30: seckill.SeckillRpc.DeleteActivity:output_type -> seckill.DeleteActivityResp
	7,  // 31: seckill.SeckillRpc.GetActivityAdmin:output_type -> seckill.GetActivityAdminResp
	9,  // 32: seckill.SeckillRpc.ListActivitiesAdmin:output_type -> seckill.ListActivitiesAdminResp
	11, // 33: seckill.SeckillRpc.UpsertActivityItem:output_type -> seckill.UpsertActivityItemResp
	13, // 34: seckill.SeckillRpc.RemoveActivityItem:output_type -> seckill.RemoveActivityItemResp
	15, // 35: seckill.SeckillRpc.PublishActivity:output_type -> seckill.PublishActivityResp
	17, // 36: seckill.SeckillRpc.OfflineActivity:output_type -> seckill.OfflineActivityResp
	19, // 37: seckill.SeckillRpc.GetActivityTraffic:output_type -> seckill.GetActivityTrafficResp
	21, // 38: seckill.SeckillRpc.ListActivityOrders:output_type -> seckill.ListActivityOrdersResp
	23, // 39: seckill.SeckillRpc.ListActivitiesPublic:output_type -> seckill.ListActivitiesPublicResp
	25, // 40: seckill.SeckillRpc.GetActivityPublic:output_type -> seckill.GetActivityPublicResp
	27, // 41: seckill.SeckillRpc.Purchase:output_type -> seckill.PurchaseResp
	29, // 42: seckill.SeckillRpc.TrackEvent:output_type -> seckill.TrackEventResp
	28, // [28:43] is the sub-list for method output_type
	13, // [13:28] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_apps_seckill_rpc_seckill_proto_init() }
func file_apps_seckill_rpc_seckill_proto_init() {
	if File_apps_seckill_rpc_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_seckill_rpc_seckill_proto_rawDesc), len(file_apps_seckill_rpc_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_seckill_rpc_seckill_proto_goTypes,
		DependencyIndexes: file_apps_seckill_rpc_seckill_proto_depIdxs,
		MessageInfos:      file_apps_seckill_rpc_seckill_proto_msgTypes,
	}.Build()
	File_apps_seckill_rpc_seckill_proto = out.File
	file_apps_seckill_rpc_seckill_proto_goTypes = nil
	file_apps_seckill_rpc_seckill_proto_depIdxs = nil
}
