// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MainImage     string                 `protobuf:"bytes,2,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCent     int64                  `protobuf:"varint,4,opt,name=price_cent,json=priceCent,proto3" json:"price_cent,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPriceCent() int64 {
	if x != nil {
		return x.PriceCent
	}
	return 0
}

func (x *CreateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *AdminProduct          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResp) GetProduct() *AdminProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MainImage     string                 `protobuf:"bytes,3,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PriceCent     int64                  `protobuf:"varint,5,opt,name=price_cent,json=priceCent,proto3" json:"price_cent,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPriceCent() int64 {
	if x != nil {
		return x.PriceCent
	}
	return 0
}

func (x *UpdateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *AdminProduct          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResp) Reset() {
	*x = UpdateProductResp{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResp) ProtoMessage() {}

func (x *UpdateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResp.ProtoReflect.Descriptor instead.
func (*UpdateProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductResp) GetProduct() *AdminProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteProductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResp) Reset() {
	*x = DeleteProductResp{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResp) ProtoMessage() {}

func (x *DeleteProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResp.ProtoReflect.Descriptor instead.
func (*DeleteProductResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAdminReq) Reset() {
	*x = GetProductAdminReq{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAdminReq) ProtoMessage() {}

func (x *GetProductAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAdminReq.ProtoReflect.Descriptor instead.
func (*GetProductAdminReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductAdminReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *AdminProduct          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAdminResp) Reset() {
	*x = GetProductAdminResp{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAdminResp) ProtoMessage() {}

func (x *GetProductAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAdminResp.ProtoReflect.Descriptor instead.
func (*GetProductAdminResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductAdminResp) GetProduct() *AdminProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsAdminReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword        string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,4,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProductsAdminReq) Reset() {
	*x = ListProductsAdminReq{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsAdminReq) ProtoMessage() {}

func (x *ListProductsAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsAdminReq.ProtoReflect.Descriptor instead.
func (*ListProductsAdminReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsAdminReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsAdminReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsAdminReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProductsAdminReq) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListProductsAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AdminProduct        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsAdminResp) Reset() {
	*x = ListProductsAdminResp{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsAdminResp) ProtoMessage() {}

func (x *ListProductsAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsAdminResp.ProtoReflect.Descriptor instead.
func (*ListProductsAdminResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsAdminResp) GetList() []*AdminProduct {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListProductsAdminResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsAdminResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsAdminResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetProductPublicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductPublicReq) Reset() {
	*x = GetProductPublicReq{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductPublicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductPublicReq) ProtoMessage() {}

func (x *GetProductPublicReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductPublicReq.ProtoReflect.Descriptor instead.
func (*GetProductPublicReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductPublicReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductPublicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *PublicProduct         `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductPublicResp) Reset() {
	*x = GetProductPublicResp{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductPublicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductPublicResp) ProtoMessage() {}

func (x *GetProductPublicResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductPublicResp.ProtoReflect.Descriptor instead.
func (*GetProductPublicResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductPublicResp) GetProduct() *PublicProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsPublicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsPublicReq) Reset() {
	*x = ListProductsPublicReq{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsPublicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsPublicReq) ProtoMessage() {}

func (x *ListProductsPublicReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsPublicReq.ProtoReflect.Descriptor instead.
func (*ListProductsPublicReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *ListProductsPublicReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsPublicReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsPublicReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListProductsPublicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PublicProduct       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsPublicResp) Reset() {
	*x = ListProductsPublicResp{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsPublicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsPublicResp) ProtoMessage() {}

func (x *ListProductsPublicResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsPublicResp.ProtoReflect.Descriptor instead.
func (*ListProductsPublicResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *ListProductsPublicResp) GetList() []*PublicProduct {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListProductsPublicResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsPublicResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsPublicResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode       string                 `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MainImage     string                 `protobuf:"bytes,4,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PriceCent     int64                  `protobuf:"varint,6,opt,name=price_cent,json=priceCent,proto3" json:"price_cent,omitempty"`
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProduct) Reset() {
	*x = AdminProduct{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProduct) ProtoMessage() {}

func (x *AdminProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProduct.ProtoReflect.Descriptor instead.
func (*AdminProduct) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *AdminProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AdminProduct) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *AdminProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminProduct) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *AdminProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminProduct) GetPriceCent() int64 {
	if x != nil {
		return x.PriceCent
	}
	return 0
}

func (x *AdminProduct) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AdminProduct) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminProduct) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *AdminProduct) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type PublicProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode       string                 `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MainImage     string                 `protobuf:"bytes,4,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PriceCent     int64                  `protobuf:"varint,6,opt,name=price_cent,json=priceCent,proto3" json:"price_cent,omitempty"`
	InStock       bool                   `protobuf:"varint,7,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicProduct) Reset() {
	*x = PublicProduct{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicProduct) ProtoMessage() {}

func (x *PublicProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicProduct.ProtoReflect.Descriptor instead.
func (*PublicProduct) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *PublicProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PublicProduct) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *PublicProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublicProduct) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *PublicProduct) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublicProduct) GetPriceCent() int64 {
	if x != nil {
		return x.PriceCent
	}
	return 0
}

func (x *PublicProduct) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\"\xb4\x01\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"main_image\x18\x02 \x01(\tR\tmainImage\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"price_cent\x18\x04 \x01(\x03R\tpriceCent\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"D\n" +
	"\x11CreateProductResp\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.product.AdminProductR\aproduct\"\xd3\x01\n" +
	"\x10UpdateProductReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"main_image\x18\x03 \x01(\tR\tmainImage\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"price_cent\x18\x05 \x01(\x03R\tpriceCent\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"D\n" +
	"\x11UpdateProductResp\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.product.AdminProductR\aproduct\"1\n" +
	"\x10DeleteProductReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"2\n" +
	"\x11DeleteProductResp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"3\n" +
	"\x12GetProductAdminReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"F\n" +
	"\x13GetProductAdminResp\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.product.AdminProductR\aproduct\"\x8a\x01\n" +
	"\x14ListProductsAdminReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12'\n" +
	"\x0finclude_deleted\x18\x04 \x01(\bR\x0eincludeDeleted\"\x89\x01\n" +
	"\x15ListProductsAdminResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.product.AdminProductR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"4\n" +
	"\x13GetProductPublicReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"H\n" +
	"\x14GetProductPublicResp\x120\n" +
	"\aproduct\x18\x01 \x01(\v2\x16.product.PublicProductR\aproduct\"b\n" +
	"\x15ListProductsPublicReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"\x8b\x01\n" +
	"\x16ListProductsPublicResp\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.product.PublicProductR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"\xba\x02\n" +
	"\fAdminProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x02 \x01(\tR\askuCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"main_image\x18\x04 \x01(\tR\tmainImage\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"price_cent\x18\x06 \x01(\x03R\tpriceCent\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12&\n" +
	"\x0fcreated_at_unix\x18\t \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\"\xd8\x01\n" +
	"\rPublicProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x02 \x01(\tR\askuCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"main_image\x18\x04 \x01(\tR\tmainImage\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"price_cent\x18\x06 \x01(\x03R\tpriceCent\x12\x19\n" +
	"\bin_stock\x18\a \x01(\bR\ainStock2\xae\x04\n" +
	"\n" +
	"ProductRpc\x12F\n" +
	"\rCreateProduct\x12\x19.product.CreateProductReq\x1a\x1a.product.CreateProductResp\x12F\n" +
	"\rUpdateProduct\x12\x19.product.UpdateProductReq\x1a\x1a.product.UpdateProductResp\x12F\n" +
	"\rDeleteProduct\x12\x19.product.DeleteProductReq\x1a\x1a.product.DeleteProductResp\x12L\n" +
	"\x0fGetProductAdmin\x12\x1b.product.GetProductAdminReq\x1a\x1c.product.GetProductAdminResp\x12R\n" +
	"\x11ListProductsAdmin\x12\x1d.product.ListProductsAdminReq\x1a\x1e.product.ListProductsAdminResp\x12O\n" +
	"\x10GetProductPublic\x12\x1c.product.GetProductPublicReq\x1a\x1d.product.GetProductPublicResp\x12U\n" +
	"\x12ListProductsPublic\x12\x1e.product.ListProductsPublicReq\x1a\x1f.product.ListProductsPublicRespB\"Z flashsale/apps/product/rpc/pb;pbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_product_proto_goTypes = []any{
	(*CreateProductReq)(nil),       // 0: product.CreateProductReq
	(*CreateProductResp)(nil),      // 1: product.CreateProductResp
	(*UpdateProductReq)(nil),       // 2: product.UpdateProductReq
	(*UpdateProductResp)(nil),      // 3: product.UpdateProductResp
	(*DeleteProductReq)(nil),       // 4: product.DeleteProductReq
	(*DeleteProductResp)(nil),      // 5: product.DeleteProductResp
	(*GetProductAdminReq)(nil),     // 6: product.GetProductAdminReq
	(*GetProductAdminResp)(nil),    // 7: product.GetProductAdminResp
	(*ListProductsAdminReq)(nil),   // 8: product.ListProductsAdminReq
	(*ListProductsAdminResp)(nil),  // 9: product.ListProductsAdminResp
	(*GetProductPublicReq)(nil),    // 10: product.GetProductPublicReq
	(*GetProductPublicResp)(nil),   // 11: product.GetProductPublicResp
	(*ListProductsPublicReq)(nil),  // 12: product.ListProductsPublicReq
	(*ListProductsPublicResp)(nil), // 13: product.ListProductsPublicResp
	(*AdminProduct)(nil),           // 14: product.AdminProduct
	(*PublicProduct)(nil),          // 15: product.PublicProduct
}
var file_product_proto_depIdxs = []int32{
	14, // 0: product.CreateProductResp.product:type_name -> product.AdminProduct
	14, // 1: product.UpdateProductResp.product:type_name -> product.AdminProduct
	14, // 2: product.GetProductAdminResp.product:type_name -> product.AdminProduct
	14, // 3: product.ListProductsAdminResp.list:type_name -> product.AdminProduct
	15, // 4: product.GetProductPublicResp.product:type_name -> product.PublicProduct
	15, // 5: product.ListProductsPublicResp.list:type_name -> product.PublicProduct
	0,  // 6: product.ProductRpc.CreateProduct:input_type -> product.CreateProductReq
	2,  // 7: product.ProductRpc.UpdateProduct:input_type -> product.UpdateProductReq
	4,  // 8: product.ProductRpc.DeleteProduct:input_type -> product.DeleteProductReq
	6,  // 9: product.ProductRpc.GetProductAdmin:input_type -> product.GetProductAdminReq
	8,  // 10: product.ProductRpc.ListProductsAdmin:input_type -> product.ListProductsAdminReq
	10, // 11: product.ProductRpc.GetProductPublic:input_type -> product.GetProductPublicReq
	12, // 12: product.ProductRpc.ListProductsPublic:input_type -> product.ListProductsPublicReq
	1,  // 13: product.ProductRpc.CreateProduct:output_type -> product.CreateProductResp
	3,  // 14: product.ProductRpc.UpdateProduct:output_type -> product.UpdateProductResp
	5,  // 15: product.ProductRpc.DeleteProduct:output_type -> product.DeleteProductResp
	7,  // 16: product.ProductRpc.GetProductAdmin:output_type -> product.GetProductAdminResp
	9,  // 17: product.ProductRpc.ListProductsAdmin:output_type -> product.ListProductsAdminResp
	11, // 18: product.ProductRpc.GetProductPublic:output_type -> product.GetProductPublicResp
	13, // 19: product.ProductRpc.ListProductsPublic:output_type -> product.ListProductsPublicResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
