// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: apps/product/rpc/product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductRpc_CreateProduct_FullMethodName           = "/product.ProductRpc/CreateProduct"
	ProductRpc_UpdateProduct_FullMethodName           = "/product.ProductRpc/UpdateProduct"
	ProductRpc_DeleteProduct_FullMethodName           = "/product.ProductRpc/DeleteProduct"
	ProductRpc_GetProductAdmin_FullMethodName         = "/product.ProductRpc/GetProductAdmin"
	ProductRpc_ListProductsAdmin_FullMethodName       = "/product.ProductRpc/ListProductsAdmin"
	ProductRpc_GetProductPublic_FullMethodName        = "/product.ProductRpc/GetProductPublic"
	ProductRpc_ListProductsPublic_FullMethodName      = "/product.ProductRpc/ListProductsPublic"
	ProductRpc_ReserveStockForOrder_FullMethodName    = "/product.ProductRpc/ReserveStockForOrder"
	ProductRpc_ReleaseStockForOrder_FullMethodName    = "/product.ProductRpc/ReleaseStockForOrder"
	ProductRpc_ReserveStockForActivity_FullMethodName = "/product.ProductRpc/ReserveStockForActivity"
	ProductRpc_ReleaseStockForActivity_FullMethodName = "/product.ProductRpc/ReleaseStockForActivity"
)

// ProductRpcClient is the client API for ProductRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductRpcClient interface {
	CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error)
	UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error)
	DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error)
	GetProductAdmin(ctx context.Context, in *GetProductAdminReq, opts ...grpc.CallOption) (*GetProductAdminResp, error)
	ListProductsAdmin(ctx context.Context, in *ListProductsAdminReq, opts ...grpc.CallOption) (*ListProductsAdminResp, error)
	GetProductPublic(ctx context.Context, in *GetProductPublicReq, opts ...grpc.CallOption) (*GetProductPublicResp, error)
	ListProductsPublic(ctx context.Context, in *ListProductsPublicReq, opts ...grpc.CallOption) (*ListProductsPublicResp, error)
	ReserveStockForOrder(ctx context.Context, in *ReserveStockForOrderReq, opts ...grpc.CallOption) (*ReserveStockForOrderResp, error)
	ReleaseStockForOrder(ctx context.Context, in *ReleaseStockForOrderReq, opts ...grpc.CallOption) (*ReleaseStockForOrderResp, error)
	ReserveStockForActivity(ctx context.Context, in *ReserveStockForActivityReq, opts ...grpc.CallOption) (*ReserveStockForActivityResp, error)
	ReleaseStockForActivity(ctx context.Context, in *ReleaseStockForActivityReq, opts ...grpc.CallOption) (*ReleaseStockForActivityResp, error)
}

type productRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewProductRpcClient(cc grpc.ClientConnInterface) ProductRpcClient {
	return &productRpcClient{cc}
}

func (c *productRpcClient) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductResp)
	err := c.cc.Invoke(ctx, ProductRpc_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductResp)
	err := c.cc.Invoke(ctx, ProductRpc_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductResp)
	err := c.cc.Invoke(ctx, ProductRpc_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) GetProductAdmin(ctx context.Context, in *GetProductAdminReq, opts ...grpc.CallOption) (*GetProductAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductAdminResp)
	err := c.cc.Invoke(ctx, ProductRpc_GetProductAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ListProductsAdmin(ctx context.Context, in *ListProductsAdminReq, opts ...grpc.CallOption) (*ListProductsAdminResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsAdminResp)
	err := c.cc.Invoke(ctx, ProductRpc_ListProductsAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) GetProductPublic(ctx context.Context, in *GetProductPublicReq, opts ...grpc.CallOption) (*GetProductPublicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductPublicResp)
	err := c.cc.Invoke(ctx, ProductRpc_GetProductPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ListProductsPublic(ctx context.Context, in *ListProductsPublicReq, opts ...grpc.CallOption) (*ListProductsPublicResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsPublicResp)
	err := c.cc.Invoke(ctx, ProductRpc_ListProductsPublic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ReserveStockForOrder(ctx context.Context, in *ReserveStockForOrderReq, opts ...grpc.CallOption) (*ReserveStockForOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveStockForOrderResp)
	err := c.cc.Invoke(ctx, ProductRpc_ReserveStockForOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ReleaseStockForOrder(ctx context.Context, in *ReleaseStockForOrderReq, opts ...grpc.CallOption) (*ReleaseStockForOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseStockForOrderResp)
	err := c.cc.Invoke(ctx, ProductRpc_ReleaseStockForOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ReserveStockForActivity(ctx context.Context, in *ReserveStockForActivityReq, opts ...grpc.CallOption) (*ReserveStockForActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveStockForActivityResp)
	err := c.cc.Invoke(ctx, ProductRpc_ReserveStockForActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productRpcClient) ReleaseStockForActivity(ctx context.Context, in *ReleaseStockForActivityReq, opts ...grpc.CallOption) (*ReleaseStockForActivityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseStockForActivityResp)
	err := c.cc.Invoke(ctx, ProductRpc_ReleaseStockForActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductRpcServer is the server API for ProductRpc service.
// All implementations must embed UnimplementedProductRpcServer
// for forward compatibility.
type ProductRpcServer interface {
	CreateProduct(context.Context, *CreateProductReq) (*CreateProductResp, error)
	UpdateProduct(context.Context, *UpdateProductReq) (*UpdateProductResp, error)
	DeleteProduct(context.Context, *DeleteProductReq) (*DeleteProductResp, error)
	GetProductAdmin(context.Context, *GetProductAdminReq) (*GetProductAdminResp, error)
	ListProductsAdmin(context.Context, *ListProductsAdminReq) (*ListProductsAdminResp, error)
	GetProductPublic(context.Context, *GetProductPublicReq) (*GetProductPublicResp, error)
	ListProductsPublic(context.Context, *ListProductsPublicReq) (*ListProductsPublicResp, error)
	ReserveStockForOrder(context.Context, *ReserveStockForOrderReq) (*ReserveStockForOrderResp, error)
	ReleaseStockForOrder(context.Context, *ReleaseStockForOrderReq) (*ReleaseStockForOrderResp, error)
	ReserveStockForActivity(context.Context, *ReserveStockForActivityReq) (*ReserveStockForActivityResp, error)
	ReleaseStockForActivity(context.Context, *ReleaseStockForActivityReq) (*ReleaseStockForActivityResp, error)
	mustEmbedUnimplementedProductRpcServer()
}

// UnimplementedProductRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductRpcServer struct{}

func (UnimplementedProductRpcServer) CreateProduct(context.Context, *CreateProductReq) (*CreateProductResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductRpcServer) UpdateProduct(context.Context, *UpdateProductReq) (*UpdateProductResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductRpcServer) DeleteProduct(context.Context, *DeleteProductReq) (*DeleteProductResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductRpcServer) GetProductAdmin(context.Context, *GetProductAdminReq) (*GetProductAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductAdmin not implemented")
}
func (UnimplementedProductRpcServer) ListProductsAdmin(context.Context, *ListProductsAdminReq) (*ListProductsAdminResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductsAdmin not implemented")
}
func (UnimplementedProductRpcServer) GetProductPublic(context.Context, *GetProductPublicReq) (*GetProductPublicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductPublic not implemented")
}
func (UnimplementedProductRpcServer) ListProductsPublic(context.Context, *ListProductsPublicReq) (*ListProductsPublicResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductsPublic not implemented")
}
func (UnimplementedProductRpcServer) ReserveStockForOrder(context.Context, *ReserveStockForOrderReq) (*ReserveStockForOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveStockForOrder not implemented")
}
func (UnimplementedProductRpcServer) ReleaseStockForOrder(context.Context, *ReleaseStockForOrderReq) (*ReleaseStockForOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseStockForOrder not implemented")
}
func (UnimplementedProductRpcServer) ReserveStockForActivity(context.Context, *ReserveStockForActivityReq) (*ReserveStockForActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveStockForActivity not implemented")
}
func (UnimplementedProductRpcServer) ReleaseStockForActivity(context.Context, *ReleaseStockForActivityReq) (*ReleaseStockForActivityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseStockForActivity not implemented")
}
func (UnimplementedProductRpcServer) mustEmbedUnimplementedProductRpcServer() {}
func (UnimplementedProductRpcServer) testEmbeddedByValue()                    {}

// UnsafeProductRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductRpcServer will
// result in compilation errors.
type UnsafeProductRpcServer interface {
	mustEmbedUnimplementedProductRpcServer()
}

func RegisterProductRpcServer(s grpc.ServiceRegistrar, srv ProductRpcServer) {
	// If the following call panics, it indicates UnimplementedProductRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductRpc_ServiceDesc, srv)
}

func _ProductRpc_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).CreateProduct(ctx, req.(*CreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).UpdateProduct(ctx, req.(*UpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).DeleteProduct(ctx, req.(*DeleteProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_GetProductAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).GetProductAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_GetProductAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).GetProductAdmin(ctx, req.(*GetProductAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ListProductsAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsAdminReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ListProductsAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ListProductsAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ListProductsAdmin(ctx, req.(*ListProductsAdminReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_GetProductPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).GetProductPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_GetProductPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).GetProductPublic(ctx, req.(*GetProductPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ListProductsPublic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsPublicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ListProductsPublic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ListProductsPublic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ListProductsPublic(ctx, req.(*ListProductsPublicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ReserveStockForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockForOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ReserveStockForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ReserveStockForOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ReserveStockForOrder(ctx, req.(*ReserveStockForOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ReleaseStockForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStockForOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ReleaseStockForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ReleaseStockForOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ReleaseStockForOrder(ctx, req.(*ReleaseStockForOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ReserveStockForActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockForActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ReserveStockForActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ReserveStockForActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ReserveStockForActivity(ctx, req.(*ReserveStockForActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductRpc_ReleaseStockForActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStockForActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductRpcServer).ReleaseStockForActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductRpc_ReleaseStockForActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductRpcServer).ReleaseStockForActivity(ctx, req.(*ReleaseStockForActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductRpc_ServiceDesc is the grpc.ServiceDesc for ProductRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductRpc",
	HandlerType: (*ProductRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductRpc_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductRpc_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductRpc_DeleteProduct_Handler,
		},
		{
			MethodName: "GetProductAdmin",
			Handler:    _ProductRpc_GetProductAdmin_Handler,
		},
		{
			MethodName: "ListProductsAdmin",
			Handler:    _ProductRpc_ListProductsAdmin_Handler,
		},
		{
			MethodName: "GetProductPublic",
			Handler:    _ProductRpc_GetProductPublic_Handler,
		},
		{
			MethodName: "ListProductsPublic",
			Handler:    _ProductRpc_ListProductsPublic_Handler,
		},
		{
			MethodName: "ReserveStockForOrder",
			Handler:    _ProductRpc_ReserveStockForOrder_Handler,
		},
		{
			MethodName: "ReleaseStockForOrder",
			Handler:    _ProductRpc_ReleaseStockForOrder_Handler,
		},
		{
			MethodName: "ReserveStockForActivity",
			Handler:    _ProductRpc_ReserveStockForActivity_Handler,
		},
		{
			MethodName: "ReleaseStockForActivity",
			Handler:    _ProductRpc_ReleaseStockForActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/product/rpc/product.proto",
}
