Name: product.rpc
ListenOn: 0.0.0.0:8084
Mode: pro
BaseConfigPath: configs/local/dev.yaml
SnowflakeNode: 2

Telemetry:
  Name: product.rpc
  Endpoint: jaeger:4317
  Sampler: 1.0
  Batcher: otlpgrpc

Etcd:
  Hosts:
    - etcd:2379
  Key: product.rpc
